// Geneza control-plane API (gateway gRPC over mTLS).
//
// Three trust levels share one listener:
//   - Enrollment: no client cert (one-time token / provider document).
//   - UserAPI.Login: no client cert (OIDC token or local credentials).
//   - NodeControl: node mTLS cert required (URI geneza://node/<id>).
//   - UserAPI (rest) / AdminAPI: user mTLS cert required (URI geneza://user/<name>).
// Enforcement is per-RPC in the gateway auth interceptor.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: geneza/v1/control.proto

package genezav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enrollment provider: "token" today; "openstack-metadata" (instance
	// identity document) is the reserved seam for the OpenStack PoC.
	Provider         string            `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Token            string            `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                               // provider=token: one-time join token
	ProviderDocument []byte            `protobuf:"bytes,3,opt,name=provider_document,json=providerDocument,proto3" json:"provider_document,omitempty"` // provider-specific identity document
	RequestedName    string            `protobuf:"bytes,4,opt,name=requested_name,json=requestedName,proto3" json:"requested_name,omitempty"`
	CsrPem           []byte            `protobuf:"bytes,5,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`                           // PKCS10 CSR for the node key (P-256)
	NoiseStaticPub   []byte            `protobuf:"bytes,6,opt,name=noise_static_pub,json=noiseStaticPub,proto3" json:"noise_static_pub,omitempty"` // 32-byte Curve25519 static public key
	Labels           map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Platform         *PlatformInfo     `protobuf:"bytes,8,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_geneza_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetProviderDocument() []byte {
	if x != nil {
		return x.ProviderDocument
	}
	return nil
}

func (x *EnrollRequest) GetRequestedName() string {
	if x != nil {
		return x.RequestedName
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *EnrollRequest) GetNoiseStaticPub() []byte {
	if x != nil {
		return x.NoiseStaticPub
	}
	return nil
}

func (x *EnrollRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *EnrollRequest) GetPlatform() *PlatformInfo {
	if x != nil {
		return x.Platform
	}
	return nil
}

type PlatformInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformInfo) Reset() {
	*x = PlatformInfo{}
	mi := &file_geneza_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformInfo) ProtoMessage() {}

func (x *PlatformInfo) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformInfo.ProtoReflect.Descriptor instead.
func (*PlatformInfo) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *PlatformInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *PlatformInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PlatformInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type EnrollResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NodeId              string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeCertPem         []byte                 `protobuf:"bytes,2,opt,name=node_cert_pem,json=nodeCertPem,proto3" json:"node_cert_pem,omitempty"`
	CaRootsPem          []byte                 `protobuf:"bytes,3,opt,name=ca_roots_pem,json=caRootsPem,proto3" json:"ca_roots_pem,omitempty"`
	SignedClusterConfig []byte                 `protobuf:"bytes,4,opt,name=signed_cluster_config,json=signedClusterConfig,proto3" json:"signed_cluster_config,omitempty"` // JSON types.Signed wrapping types.ClusterConfig
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_geneza_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EnrollResponse) GetNodeCertPem() []byte {
	if x != nil {
		return x.NodeCertPem
	}
	return nil
}

func (x *EnrollResponse) GetCaRootsPem() []byte {
	if x != nil {
		return x.CaRootsPem
	}
	return nil
}

func (x *EnrollResponse) GetSignedClusterConfig() []byte {
	if x != nil {
		return x.SignedClusterConfig
	}
	return nil
}

type AgentMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMsg_Hello
	//	*AgentMsg_Heartbeat
	//	*AgentMsg_SessionEvent
	//	*AgentMsg_OfferAck
	Msg           isAgentMsg_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMsg) Reset() {
	*x = AgentMsg{}
	mi := &file_geneza_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMsg) ProtoMessage() {}

func (x *AgentMsg) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMsg.ProtoReflect.Descriptor instead.
func (*AgentMsg) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *AgentMsg) GetMsg() isAgentMsg_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMsg) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Msg.(*AgentMsg_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMsg) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentMsg_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMsg) GetSessionEvent() *SessionEvent {
	if x != nil {
		if x, ok := x.Msg.(*AgentMsg_SessionEvent); ok {
			return x.SessionEvent
		}
	}
	return nil
}

func (x *AgentMsg) GetOfferAck() *SessionOfferAck {
	if x != nil {
		if x, ok := x.Msg.(*AgentMsg_OfferAck); ok {
			return x.OfferAck
		}
	}
	return nil
}

type isAgentMsg_Msg interface {
	isAgentMsg_Msg()
}

type AgentMsg_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMsg_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMsg_SessionEvent struct {
	SessionEvent *SessionEvent `protobuf:"bytes,3,opt,name=session_event,json=sessionEvent,proto3,oneof"`
}

type AgentMsg_OfferAck struct {
	OfferAck *SessionOfferAck `protobuf:"bytes,4,opt,name=offer_ack,json=offerAck,proto3,oneof"`
}

func (*AgentMsg_Hello) isAgentMsg_Msg() {}

func (*AgentMsg_Heartbeat) isAgentMsg_Msg() {}

func (*AgentMsg_SessionEvent) isAgentMsg_Msg() {}

func (*AgentMsg_OfferAck) isAgentMsg_Msg() {}

type GatewayMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GatewayMsg_SessionOffer
	//	*GatewayMsg_ClusterConfig
	//	*GatewayMsg_Ping
	Msg           isGatewayMsg_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMsg) Reset() {
	*x = GatewayMsg{}
	mi := &file_geneza_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMsg) ProtoMessage() {}

func (x *GatewayMsg) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMsg.ProtoReflect.Descriptor instead.
func (*GatewayMsg) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *GatewayMsg) GetMsg() isGatewayMsg_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GatewayMsg) GetSessionOffer() *SessionOffer {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMsg_SessionOffer); ok {
			return x.SessionOffer
		}
	}
	return nil
}

func (x *GatewayMsg) GetClusterConfig() []byte {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMsg_ClusterConfig); ok {
			return x.ClusterConfig
		}
	}
	return nil
}

func (x *GatewayMsg) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*GatewayMsg_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isGatewayMsg_Msg interface {
	isGatewayMsg_Msg()
}

type GatewayMsg_SessionOffer struct {
	SessionOffer *SessionOffer `protobuf:"bytes,1,opt,name=session_offer,json=sessionOffer,proto3,oneof"`
}

type GatewayMsg_ClusterConfig struct {
	ClusterConfig []byte `protobuf:"bytes,2,opt,name=cluster_config,json=clusterConfig,proto3,oneof"` // JSON types.Signed wrapping types.ClusterConfig
}

type GatewayMsg_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*GatewayMsg_SessionOffer) isGatewayMsg_Msg() {}

func (*GatewayMsg_ClusterConfig) isGatewayMsg_Msg() {}

func (*GatewayMsg_Ping) isGatewayMsg_Msg() {}

type AgentHello struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeId               string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version              string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Labels               map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capabilities         []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                                                // e.g. "shell","exec","sftp","forward","attach"
	ClusterConfigVersion int64                  `protobuf:"varint,5,opt,name=cluster_config_version,json=clusterConfigVersion,proto3" json:"cluster_config_version,omitempty"` // version agent currently holds
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_geneza_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *AgentHello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentHello) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentHello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentHello) GetClusterConfigVersion() int64 {
	if x != nil {
		return x.ClusterConfigVersion
	}
	return 0
}

type Heartbeat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UnixMs           int64                  `protobuf:"varint,1,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	ActiveSessions   uint32                 `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	DetachedSessions uint32                 `protobuf:"varint,3,opt,name=detached_sessions,json=detachedSessions,proto3" json:"detached_sessions,omitempty"`
	Version          string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Healthy          bool                   `protobuf:"varint,5,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_geneza_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

func (x *Heartbeat) GetActiveSessions() uint32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *Heartbeat) GetDetachedSessions() uint32 {
	if x != nil {
		return x.DetachedSessions
	}
	return 0
}

func (x *Heartbeat) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Heartbeat) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

// signed_grant is a JSON types.Signed wrapping types.SessionGrant; it contains
// everything the agent needs (relay addr+token, client noise key, scope).
type SessionOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedGrant   []byte                 `protobuf:"bytes,1,opt,name=signed_grant,json=signedGrant,proto3" json:"signed_grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOffer) Reset() {
	*x = SessionOffer{}
	mi := &file_geneza_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOffer) ProtoMessage() {}

func (x *SessionOffer) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOffer.ProtoReflect.Descriptor instead.
func (*SessionOffer) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *SessionOffer) GetSignedGrant() []byte {
	if x != nil {
		return x.SignedGrant
	}
	return nil
}

type SessionOfferAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOfferAck) Reset() {
	*x = SessionOfferAck{}
	mi := &file_geneza_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOfferAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOfferAck) ProtoMessage() {}

func (x *SessionOfferAck) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOfferAck.ProtoReflect.Descriptor instead.
func (*SessionOfferAck) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *SessionOfferAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionOfferAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SessionOfferAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Session lifecycle events for the audit trail (emitted by the agent).
// event: offered|established|attached|detached|ended|rejected
type SessionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	UnixMs        int64                  `protobuf:"varint,4,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	HostSessionId string                 `protobuf:"bytes,5,opt,name=host_session_id,json=hostSessionId,proto3" json:"host_session_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_geneza_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *SessionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *SessionEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *SessionEvent) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

func (x *SessionEvent) GetHostSessionId() string {
	if x != nil {
		return x.HostSessionId
	}
	return ""
}

func (x *SessionEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type RecordingChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingChunk) Reset() {
	*x = RecordingChunk{}
	mi := &file_geneza_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingChunk) ProtoMessage() {}

func (x *RecordingChunk) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingChunk.ProtoReflect.Descriptor instead.
func (*RecordingChunk) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *RecordingChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecordingChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RecordingChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type UploadAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAck) Reset() {
	*x = UploadAck{}
	mi := &file_geneza_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAck) ProtoMessage() {}

func (x *UploadAck) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAck.ProtoReflect.Descriptor instead.
func (*UploadAck) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *UploadAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RenewCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrPem        []byte                 `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertRequest) Reset() {
	*x = RenewCertRequest{}
	mi := &file_geneza_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertRequest) ProtoMessage() {}

func (x *RenewCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertRequest.ProtoReflect.Descriptor instead.
func (*RenewCertRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *RenewCertRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type RenewCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeCertPem   []byte                 `protobuf:"bytes,1,opt,name=node_cert_pem,json=nodeCertPem,proto3" json:"node_cert_pem,omitempty"`
	CaRootsPem    []byte                 `protobuf:"bytes,2,opt,name=ca_roots_pem,json=caRootsPem,proto3" json:"ca_roots_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertResponse) Reset() {
	*x = RenewCertResponse{}
	mi := &file_geneza_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertResponse) ProtoMessage() {}

func (x *RenewCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertResponse.ProtoReflect.Descriptor instead.
func (*RenewCertResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *RenewCertResponse) GetNodeCertPem() []byte {
	if x != nil {
		return x.NodeCertPem
	}
	return nil
}

func (x *RenewCertResponse) GetCaRootsPem() []byte {
	if x != nil {
		return x.CaRootsPem
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixMs        int64                  `protobuf:"varint,1,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_geneza_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *Ping) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                            // "oidc" | "local"
	OidcIdToken   string                 `protobuf:"bytes,2,opt,name=oidc_id_token,json=oidcIdToken,proto3" json:"oidc_id_token,omitempty"` // provider=oidc: raw ID token JWT (client ran the flow)
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                            // provider=local
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CsrPem        []byte                 `protobuf:"bytes,5,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"` // PKCS10 CSR for the client-held key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_geneza_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *LoginRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LoginRequest) GetOidcIdToken() string {
	if x != nil {
		return x.OidcIdToken
	}
	return ""
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCertPem   []byte                 `protobuf:"bytes,1,opt,name=user_cert_pem,json=userCertPem,proto3" json:"user_cert_pem,omitempty"`
	CaRootsPem    []byte                 `protobuf:"bytes,2,opt,name=ca_roots_pem,json=caRootsPem,proto3" json:"ca_roots_pem,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	ExpiresUnix   int64                  `protobuf:"varint,5,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_geneza_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *LoginResponse) GetUserCertPem() []byte {
	if x != nil {
		return x.UserCertPem
	}
	return nil
}

func (x *LoginResponse) GetCaRootsPem() []byte {
	if x != nil {
		return x.CaRootsPem
	}
	return nil
}

func (x *LoginResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *LoginResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *LoginResponse) GetExpiresUnix() int64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

type NodeSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels           map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Online           bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	Version          string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Os               string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Arch             string                 `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`
	LastSeenUnix     int64                  `protobuf:"varint,8,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	ActiveSessions   uint32                 `protobuf:"varint,9,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	DetachedSessions uint32                 `protobuf:"varint,10,opt,name=detached_sessions,json=detachedSessions,proto3" json:"detached_sessions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeSummary) Reset() {
	*x = NodeSummary{}
	mi := &file_geneza_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSummary) ProtoMessage() {}

func (x *NodeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSummary.ProtoReflect.Descriptor instead.
func (*NodeSummary) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *NodeSummary) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeSummary) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *NodeSummary) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *NodeSummary) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeSummary) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *NodeSummary) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *NodeSummary) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *NodeSummary) GetActiveSessions() uint32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *NodeSummary) GetDetachedSessions() uint32 {
	if x != nil {
		return x.DetachedSessions
	}
	return 0
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_geneza_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{18}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeSummary         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_geneza_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *ListNodesResponse) GetNodes() []*NodeSummary {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type CreateSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Node            string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`       // node id or name
	Action          string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`   // shell|exec|sftp|forward|attach
	Command         string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"` // action=exec
	WantPty         bool                   `protobuf:"varint,4,opt,name=want_pty,json=wantPty,proto3" json:"want_pty,omitempty"`
	WantDetachable  bool                   `protobuf:"varint,5,opt,name=want_detachable,json=wantDetachable,proto3" json:"want_detachable,omitempty"`
	AttachSessionId string                 `protobuf:"bytes,6,opt,name=attach_session_id,json=attachSessionId,proto3" json:"attach_session_id,omitempty"` // action=attach: host session id to reattach
	ForwardTarget   string                 `protobuf:"bytes,7,opt,name=forward_target,json=forwardTarget,proto3" json:"forward_target,omitempty"`         // action=forward: host:port on the node side
	ClientNoisePub  []byte                 `protobuf:"bytes,8,opt,name=client_noise_pub,json=clientNoisePub,proto3" json:"client_noise_pub,omitempty"`    // 32-byte Curve25519 static public key
	ClientPath      string                 `protobuf:"bytes,9,opt,name=client_path,json=clientPath,proto3" json:"client_path,omitempty"`                  // "native" | "web"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_geneza_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *CreateSessionRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *CreateSessionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreateSessionRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateSessionRequest) GetWantPty() bool {
	if x != nil {
		return x.WantPty
	}
	return false
}

func (x *CreateSessionRequest) GetWantDetachable() bool {
	if x != nil {
		return x.WantDetachable
	}
	return false
}

func (x *CreateSessionRequest) GetAttachSessionId() string {
	if x != nil {
		return x.AttachSessionId
	}
	return ""
}

func (x *CreateSessionRequest) GetForwardTarget() string {
	if x != nil {
		return x.ForwardTarget
	}
	return ""
}

func (x *CreateSessionRequest) GetClientNoisePub() []byte {
	if x != nil {
		return x.ClientNoisePub
	}
	return nil
}

func (x *CreateSessionRequest) GetClientPath() string {
	if x != nil {
		return x.ClientPath
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedGrant   []byte                 `protobuf:"bytes,1,opt,name=signed_grant,json=signedGrant,proto3" json:"signed_grant,omitempty"` // JSON types.Signed wrapping types.SessionGrant
	RelayAddr     string                 `protobuf:"bytes,2,opt,name=relay_addr,json=relayAddr,proto3" json:"relay_addr,omitempty"`
	RelayToken    string                 `protobuf:"bytes,3,opt,name=relay_token,json=relayToken,proto3" json:"relay_token,omitempty"`
	AgentNoisePub []byte                 `protobuf:"bytes,4,opt,name=agent_noise_pub,json=agentNoisePub,proto3" json:"agent_noise_pub,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_geneza_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{21}
}

func (x *CreateSessionResponse) GetSignedGrant() []byte {
	if x != nil {
		return x.SignedGrant
	}
	return nil
}

func (x *CreateSessionResponse) GetRelayAddr() string {
	if x != nil {
		return x.RelayAddr
	}
	return ""
}

func (x *CreateSessionResponse) GetRelayToken() string {
	if x != nil {
		return x.RelayToken
	}
	return ""
}

func (x *CreateSessionResponse) GetAgentNoisePub() []byte {
	if x != nil {
		return x.AgentNoisePub
	}
	return nil
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"` // pending|active|detached|ended
	StartedUnix   int64                  `protobuf:"varint,7,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`
	HostSessionId string                 `protobuf:"bytes,8,opt,name=host_session_id,json=hostSessionId,proto3" json:"host_session_id,omitempty"`
	Detachable    bool                   `protobuf:"varint,9,opt,name=detachable,proto3" json:"detachable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_geneza_v1_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{22}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SessionInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *SessionInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SessionInfo) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SessionInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SessionInfo) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *SessionInfo) GetHostSessionId() string {
	if x != nil {
		return x.HostSessionId
	}
	return ""
}

func (x *SessionInfo) GetDetachable() bool {
	if x != nil {
		return x.Detachable
	}
	return false
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MineOnly      bool                   `protobuf:"varint,1,opt,name=mine_only,json=mineOnly,proto3" json:"mine_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_geneza_v1_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{23}
}

func (x *ListSessionsRequest) GetMineOnly() bool {
	if x != nil {
		return x.MineOnly
	}
	return false
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_geneza_v1_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{24}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type WhoAmIResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	User            string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Roles           []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	CertExpiresUnix int64                  `protobuf:"varint,3,opt,name=cert_expires_unix,json=certExpiresUnix,proto3" json:"cert_expires_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_geneza_v1_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{25}
}

func (x *WhoAmIResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *WhoAmIResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *WhoAmIResponse) GetCertExpiresUnix() int64 {
	if x != nil {
		return x.CertExpiresUnix
	}
	return 0
}

type CreateJoinTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TtlSeconds    int64                  `protobuf:"varint,1,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`                                                // default 3600
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // labels stamped onto the enrolling node
	MaxUses       int32                  `protobuf:"varint,3,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`                                                         // default 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenRequest) Reset() {
	*x = CreateJoinTokenRequest{}
	mi := &file_geneza_v1_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenRequest) ProtoMessage() {}

func (x *CreateJoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{26}
}

func (x *CreateJoinTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *CreateJoinTokenRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateJoinTokenRequest) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

type CreateJoinTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresUnix   int64                  `protobuf:"varint,2,opt,name=expires_unix,json=expiresUnix,proto3" json:"expires_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenResponse) Reset() {
	*x = CreateJoinTokenResponse{}
	mi := &file_geneza_v1_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenResponse) ProtoMessage() {}

func (x *CreateJoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{27}
}

func (x *CreateJoinTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateJoinTokenResponse) GetExpiresUnix() int64 {
	if x != nil {
		return x.ExpiresUnix
	}
	return 0
}

// First chunk must carry signed_manifest (JSON types.Signed wrapping
// types.Manifest, signed OFFLINE by the artifact key); the gateway verifies
// the blob hash against the manifest before accepting. The gateway does NOT
// hold the artifact signing key.
type ArtifactChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SignedManifest []byte                 `protobuf:"bytes,1,opt,name=signed_manifest,json=signedManifest,proto3" json:"signed_manifest,omitempty"`
	Data           []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Eof            bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArtifactChunk) Reset() {
	*x = ArtifactChunk{}
	mi := &file_geneza_v1_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactChunk) ProtoMessage() {}

func (x *ArtifactChunk) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactChunk.ProtoReflect.Descriptor instead.
func (*ArtifactChunk) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{28}
}

func (x *ArtifactChunk) GetSignedManifest() []byte {
	if x != nil {
		return x.SignedManifest
	}
	return nil
}

func (x *ArtifactChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ArtifactChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type PublishArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishArtifactResponse) Reset() {
	*x = PublishArtifactResponse{}
	mi := &file_geneza_v1_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishArtifactResponse) ProtoMessage() {}

func (x *PublishArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishArtifactResponse.ProtoReflect.Descriptor instead.
func (*PublishArtifactResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{29}
}

func (x *PublishArtifactResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PublishArtifactResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type SetDesiredVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ring          string                 `protobuf:"bytes,1,opt,name=ring,proto3" json:"ring,omitempty"` // "canary" | "stable"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	CanaryNodes   []string               `protobuf:"bytes,3,rep,name=canary_nodes,json=canaryNodes,proto3" json:"canary_nodes,omitempty"` // optional: set the canary ring membership
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDesiredVersionRequest) Reset() {
	*x = SetDesiredVersionRequest{}
	mi := &file_geneza_v1_control_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDesiredVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDesiredVersionRequest) ProtoMessage() {}

func (x *SetDesiredVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDesiredVersionRequest.ProtoReflect.Descriptor instead.
func (*SetDesiredVersionRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{30}
}

func (x *SetDesiredVersionRequest) GetRing() string {
	if x != nil {
		return x.Ring
	}
	return ""
}

func (x *SetDesiredVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SetDesiredVersionRequest) GetCanaryNodes() []string {
	if x != nil {
		return x.CanaryNodes
	}
	return nil
}

type FleetStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeSummary         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	StableVersion string                 `protobuf:"bytes,2,opt,name=stable_version,json=stableVersion,proto3" json:"stable_version,omitempty"`
	CanaryVersion string                 `protobuf:"bytes,3,opt,name=canary_version,json=canaryVersion,proto3" json:"canary_version,omitempty"`
	CanaryNodes   []string               `protobuf:"bytes,4,rep,name=canary_nodes,json=canaryNodes,proto3" json:"canary_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetStatus) Reset() {
	*x = FleetStatus{}
	mi := &file_geneza_v1_control_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetStatus) ProtoMessage() {}

func (x *FleetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetStatus.ProtoReflect.Descriptor instead.
func (*FleetStatus) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{31}
}

func (x *FleetStatus) GetNodes() []*NodeSummary {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *FleetStatus) GetStableVersion() string {
	if x != nil {
		return x.StableVersion
	}
	return ""
}

func (x *FleetStatus) GetCanaryVersion() string {
	if x != nil {
		return x.CanaryVersion
	}
	return ""
}

func (x *FleetStatus) GetCanaryNodes() []string {
	if x != nil {
		return x.CanaryNodes
	}
	return nil
}

type QueryAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceUnix     int64                  `protobuf:"varint,1,opt,name=since_unix,json=sinceUnix,proto3" json:"since_unix,omitempty"`
	TypeFilter    string                 `protobuf:"bytes,2,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // default 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditRequest) Reset() {
	*x = QueryAuditRequest{}
	mi := &file_geneza_v1_control_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditRequest) ProtoMessage() {}

func (x *QueryAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditRequest.ProtoReflect.Descriptor instead.
func (*QueryAuditRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{32}
}

func (x *QueryAuditRequest) GetSinceUnix() int64 {
	if x != nil {
		return x.SinceUnix
	}
	return 0
}

func (x *QueryAuditRequest) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

func (x *QueryAuditRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AuditRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // raw audit record (hash-chained JSONL line)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_geneza_v1_control_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{33}
}

func (x *AuditRecord) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type QueryAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*AuditRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	ChainOk       bool                   `protobuf:"varint,2,opt,name=chain_ok,json=chainOk,proto3" json:"chain_ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAuditResponse) Reset() {
	*x = QueryAuditResponse{}
	mi := &file_geneza_v1_control_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAuditResponse) ProtoMessage() {}

func (x *QueryAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAuditResponse.ProtoReflect.Descriptor instead.
func (*QueryAuditResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{34}
}

func (x *QueryAuditResponse) GetRecords() []*AuditRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *QueryAuditResponse) GetChainOk() bool {
	if x != nil {
		return x.ChainOk
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_geneza_v1_control_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_control_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_geneza_v1_control_proto_rawDescGZIP(), []int{35}
}

var File_geneza_v1_control_proto protoreflect.FileDescriptor

const file_geneza_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x17geneza/v1/control.proto\x12\tgeneza.v1\"\x86\x03\n" +
	"\rEnrollRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12+\n" +
	"\x11provider_document\x18\x03 \x01(\fR\x10providerDocument\x12%\n" +
	"\x0erequested_name\x18\x04 \x01(\tR\rrequestedName\x12\x17\n" +
	"\acsr_pem\x18\x05 \x01(\fR\x06csrPem\x12(\n" +
	"\x10noise_static_pub\x18\x06 \x01(\fR\x0enoiseStaticPub\x12<\n" +
	"\x06labels\x18\a \x03(\v2$.geneza.v1.EnrollRequest.LabelsEntryR\x06labels\x123\n" +
	"\bplatform\x18\b \x01(\v2\x17.geneza.v1.PlatformInfoR\bplatform\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\fPlatformInfo\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"\xa3\x01\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\"\n" +
	"\rnode_cert_pem\x18\x02 \x01(\fR\vnodeCertPem\x12 \n" +
	"\fca_roots_pem\x18\x03 \x01(\fR\n" +
	"caRootsPem\x122\n" +
	"\x15signed_cluster_config\x18\x04 \x01(\fR\x13signedClusterConfig\"\xf1\x01\n" +
	"\bAgentMsg\x12-\n" +
	"\x05hello\x18\x01 \x01(\v2\x15.geneza.v1.AgentHelloH\x00R\x05hello\x124\n" +
	"\theartbeat\x18\x02 \x01(\v2\x14.geneza.v1.HeartbeatH\x00R\theartbeat\x12>\n" +
	"\rsession_event\x18\x03 \x01(\v2\x17.geneza.v1.SessionEventH\x00R\fsessionEvent\x129\n" +
	"\toffer_ack\x18\x04 \x01(\v2\x1a.geneza.v1.SessionOfferAckH\x00R\bofferAckB\x05\n" +
	"\x03msg\"\xa3\x01\n" +
	"\n" +
	"GatewayMsg\x12>\n" +
	"\rsession_offer\x18\x01 \x01(\v2\x17.geneza.v1.SessionOfferH\x00R\fsessionOffer\x12'\n" +
	"\x0ecluster_config\x18\x02 \x01(\fH\x00R\rclusterConfig\x12%\n" +
	"\x04ping\x18\x03 \x01(\v2\x0f.geneza.v1.PingH\x00R\x04pingB\x05\n" +
	"\x03msg\"\x8f\x02\n" +
	"\n" +
	"AgentHello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x129\n" +
	"\x06labels\x18\x03 \x03(\v2!.geneza.v1.AgentHello.LabelsEntryR\x06labels\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x124\n" +
	"\x16cluster_config_version\x18\x05 \x01(\x03R\x14clusterConfigVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\aunix_ms\x18\x01 \x01(\x03R\x06unixMs\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\rR\x0eactiveSessions\x12+\n" +
	"\x11detached_sessions\x18\x03 \x01(\rR\x10detachedSessions\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x18\n" +
	"\ahealthy\x18\x05 \x01(\bR\ahealthy\"1\n" +
	"\fSessionOffer\x12!\n" +
	"\fsigned_grant\x18\x01 \x01(\fR\vsignedGrant\"d\n" +
	"\x0fSessionOfferAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xb9\x01\n" +
	"\fSessionEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x17\n" +
	"\aunix_ms\x18\x04 \x01(\x03R\x06unixMs\x12&\n" +
	"\x0fhost_session_id\x18\x05 \x01(\tR\rhostSessionId\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\"U\n" +
	"\x0eRecordingChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"\x1b\n" +
	"\tUploadAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"+\n" +
	"\x10RenewCertRequest\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\fR\x06csrPem\"Y\n" +
	"\x11RenewCertResponse\x12\"\n" +
	"\rnode_cert_pem\x18\x01 \x01(\fR\vnodeCertPem\x12 \n" +
	"\fca_roots_pem\x18\x02 \x01(\fR\n" +
	"caRootsPem\"\x1f\n" +
	"\x04Ping\x12\x17\n" +
	"\aunix_ms\x18\x01 \x01(\x03R\x06unixMs\"\x9f\x01\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\"\n" +
	"\roidc_id_token\x18\x02 \x01(\tR\voidcIdToken\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x17\n" +
	"\acsr_pem\x18\x05 \x01(\fR\x06csrPem\"\xa2\x01\n" +
	"\rLoginResponse\x12\"\n" +
	"\ruser_cert_pem\x18\x01 \x01(\fR\vuserCertPem\x12 \n" +
	"\fca_roots_pem\x18\x02 \x01(\fR\n" +
	"caRootsPem\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12!\n" +
	"\fexpires_unix\x18\x05 \x01(\x03R\vexpiresUnix\"\x83\x03\n" +
	"\vNodeSummary\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\x06labels\x18\x03 \x03(\v2\".geneza.v1.NodeSummary.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\a \x01(\tR\x04arch\x12$\n" +
	"\x0elast_seen_unix\x18\b \x01(\x03R\flastSeenUnix\x12'\n" +
	"\x0factive_sessions\x18\t \x01(\rR\x0eactiveSessions\x12+\n" +
	"\x11detached_sessions\x18\n" +
	" \x01(\rR\x10detachedSessions\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x12\n" +
	"\x10ListNodesRequest\"A\n" +
	"\x11ListNodesResponse\x12,\n" +
	"\x05nodes\x18\x01 \x03(\v2\x16.geneza.v1.NodeSummaryR\x05nodes\"\xbe\x02\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x19\n" +
	"\bwant_pty\x18\x04 \x01(\bR\awantPty\x12'\n" +
	"\x0fwant_detachable\x18\x05 \x01(\bR\x0ewantDetachable\x12*\n" +
	"\x11attach_session_id\x18\x06 \x01(\tR\x0fattachSessionId\x12%\n" +
	"\x0eforward_target\x18\a \x01(\tR\rforwardTarget\x12(\n" +
	"\x10client_noise_pub\x18\b \x01(\fR\x0eclientNoisePub\x12\x1f\n" +
	"\vclient_path\x18\t \x01(\tR\n" +
	"clientPath\"\xc1\x01\n" +
	"\x15CreateSessionResponse\x12!\n" +
	"\fsigned_grant\x18\x01 \x01(\fR\vsignedGrant\x12\x1d\n" +
	"\n" +
	"relay_addr\x18\x02 \x01(\tR\trelayAddr\x12\x1f\n" +
	"\vrelay_token\x18\x03 \x01(\tR\n" +
	"relayToken\x12&\n" +
	"\x0fagent_noise_pub\x18\x04 \x01(\fR\ragentNoisePub\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"\x8f\x02\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12!\n" +
	"\fstarted_unix\x18\a \x01(\x03R\vstartedUnix\x12&\n" +
	"\x0fhost_session_id\x18\b \x01(\tR\rhostSessionId\x12\x1e\n" +
	"\n" +
	"detachable\x18\t \x01(\bR\n" +
	"detachable\"2\n" +
	"\x13ListSessionsRequest\x12\x1b\n" +
	"\tmine_only\x18\x01 \x01(\bR\bmineOnly\"J\n" +
	"\x14ListSessionsResponse\x122\n" +
	"\bsessions\x18\x01 \x03(\v2\x16.geneza.v1.SessionInfoR\bsessions\"f\n" +
	"\x0eWhoAmIResponse\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12*\n" +
	"\x11cert_expires_unix\x18\x03 \x01(\x03R\x0fcertExpiresUnix\"\xd6\x01\n" +
	"\x16CreateJoinTokenRequest\x12\x1f\n" +
	"\vttl_seconds\x18\x01 \x01(\x03R\n" +
	"ttlSeconds\x12E\n" +
	"\x06labels\x18\x02 \x03(\v2-.geneza.v1.CreateJoinTokenRequest.LabelsEntryR\x06labels\x12\x19\n" +
	"\bmax_uses\x18\x03 \x01(\x05R\amaxUses\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x17CreateJoinTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fexpires_unix\x18\x02 \x01(\x03R\vexpiresUnix\"^\n" +
	"\rArtifactChunk\x12'\n" +
	"\x0fsigned_manifest\x18\x01 \x01(\fR\x0esignedManifest\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"K\n" +
	"\x17PublishArtifactResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"k\n" +
	"\x18SetDesiredVersionRequest\x12\x12\n" +
	"\x04ring\x18\x01 \x01(\tR\x04ring\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fcanary_nodes\x18\x03 \x03(\tR\vcanaryNodes\"\xac\x01\n" +
	"\vFleetStatus\x12,\n" +
	"\x05nodes\x18\x01 \x03(\v2\x16.geneza.v1.NodeSummaryR\x05nodes\x12%\n" +
	"\x0estable_version\x18\x02 \x01(\tR\rstableVersion\x12%\n" +
	"\x0ecanary_version\x18\x03 \x01(\tR\rcanaryVersion\x12!\n" +
	"\fcanary_nodes\x18\x04 \x03(\tR\vcanaryNodes\"i\n" +
	"\x11QueryAuditRequest\x12\x1d\n" +
	"\n" +
	"since_unix\x18\x01 \x01(\x03R\tsinceUnix\x12\x1f\n" +
	"\vtype_filter\x18\x02 \x01(\tR\n" +
	"typeFilter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"!\n" +
	"\vAuditRecord\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"a\n" +
	"\x12QueryAuditResponse\x120\n" +
	"\arecords\x18\x01 \x03(\v2\x16.geneza.v1.AuditRecordR\arecords\x12\x19\n" +
	"\bchain_ok\x18\x02 \x01(\bR\achainOk\"\a\n" +
	"\x05Empty2K\n" +
	"\n" +
	"Enrollment\x12=\n" +
	"\x06Enroll\x12\x18.geneza.v1.EnrollRequest\x1a\x19.geneza.v1.EnrollResponse2\xd5\x01\n" +
	"\vNodeControl\x128\n" +
	"\x06Stream\x12\x13.geneza.v1.AgentMsg\x1a\x15.geneza.v1.GatewayMsg(\x010\x01\x12F\n" +
	"\tRenewCert\x12\x1b.geneza.v1.RenewCertRequest\x1a\x1c.geneza.v1.RenewCertResponse\x12D\n" +
	"\x0fUploadRecording\x12\x19.geneza.v1.RecordingChunk\x1a\x14.geneza.v1.UploadAck(\x012\xe9\x02\n" +
	"\aUserAPI\x12:\n" +
	"\x05Login\x12\x17.geneza.v1.LoginRequest\x1a\x18.geneza.v1.LoginResponse\x12F\n" +
	"\tListNodes\x12\x1b.geneza.v1.ListNodesRequest\x1a\x1c.geneza.v1.ListNodesResponse\x12R\n" +
	"\rCreateSession\x12\x1f.geneza.v1.CreateSessionRequest\x1a .geneza.v1.CreateSessionResponse\x12O\n" +
	"\fListSessions\x12\x1e.geneza.v1.ListSessionsRequest\x1a\x1f.geneza.v1.ListSessionsResponse\x125\n" +
	"\x06WhoAmI\x12\x10.geneza.v1.Empty\x1a\x19.geneza.v1.WhoAmIResponse2\xbe\x03\n" +
	"\bAdminAPI\x12X\n" +
	"\x0fCreateJoinToken\x12!.geneza.v1.CreateJoinTokenRequest\x1a\".geneza.v1.CreateJoinTokenResponse\x12Q\n" +
	"\x0fPublishArtifact\x12\x18.geneza.v1.ArtifactChunk\x1a\".geneza.v1.PublishArtifactResponse(\x01\x12J\n" +
	"\x11SetDesiredVersion\x12#.geneza.v1.SetDesiredVersionRequest\x1a\x10.geneza.v1.Empty\x12:\n" +
	"\x0eGetFleetStatus\x12\x10.geneza.v1.Empty\x1a\x16.geneza.v1.FleetStatus\x122\n" +
	"\fReloadPolicy\x12\x10.geneza.v1.Empty\x1a\x10.geneza.v1.Empty\x12I\n" +
	"\n" +
	"QueryAudit\x12\x1c.geneza.v1.QueryAuditRequest\x1a\x1d.geneza.v1.QueryAuditResponseB2Z0osie.cloud/geneza/internal/pb/geneza/v1;genezav1b\x06proto3"

var (
	file_geneza_v1_control_proto_rawDescOnce sync.Once
	file_geneza_v1_control_proto_rawDescData []byte
)

func file_geneza_v1_control_proto_rawDescGZIP() []byte {
	file_geneza_v1_control_proto_rawDescOnce.Do(func() {
		file_geneza_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geneza_v1_control_proto_rawDesc), len(file_geneza_v1_control_proto_rawDesc)))
	})
	return file_geneza_v1_control_proto_rawDescData
}

var file_geneza_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_geneza_v1_control_proto_goTypes = []any{
	(*EnrollRequest)(nil),            // 0: geneza.v1.EnrollRequest
	(*PlatformInfo)(nil),             // 1: geneza.v1.PlatformInfo
	(*EnrollResponse)(nil),           // 2: geneza.v1.EnrollResponse
	(*AgentMsg)(nil),                 // 3: geneza.v1.AgentMsg
	(*GatewayMsg)(nil),               // 4: geneza.v1.GatewayMsg
	(*AgentHello)(nil),               // 5: geneza.v1.AgentHello
	(*Heartbeat)(nil),                // 6: geneza.v1.Heartbeat
	(*SessionOffer)(nil),             // 7: geneza.v1.SessionOffer
	(*SessionOfferAck)(nil),          // 8: geneza.v1.SessionOfferAck
	(*SessionEvent)(nil),             // 9: geneza.v1.SessionEvent
	(*RecordingChunk)(nil),           // 10: geneza.v1.RecordingChunk
	(*UploadAck)(nil),                // 11: geneza.v1.UploadAck
	(*RenewCertRequest)(nil),         // 12: geneza.v1.RenewCertRequest
	(*RenewCertResponse)(nil),        // 13: geneza.v1.RenewCertResponse
	(*Ping)(nil),                     // 14: geneza.v1.Ping
	(*LoginRequest)(nil),             // 15: geneza.v1.LoginRequest
	(*LoginResponse)(nil),            // 16: geneza.v1.LoginResponse
	(*NodeSummary)(nil),              // 17: geneza.v1.NodeSummary
	(*ListNodesRequest)(nil),         // 18: geneza.v1.ListNodesRequest
	(*ListNodesResponse)(nil),        // 19: geneza.v1.ListNodesResponse
	(*CreateSessionRequest)(nil),     // 20: geneza.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),    // 21: geneza.v1.CreateSessionResponse
	(*SessionInfo)(nil),              // 22: geneza.v1.SessionInfo
	(*ListSessionsRequest)(nil),      // 23: geneza.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),     // 24: geneza.v1.ListSessionsResponse
	(*WhoAmIResponse)(nil),           // 25: geneza.v1.WhoAmIResponse
	(*CreateJoinTokenRequest)(nil),   // 26: geneza.v1.CreateJoinTokenRequest
	(*CreateJoinTokenResponse)(nil),  // 27: geneza.v1.CreateJoinTokenResponse
	(*ArtifactChunk)(nil),            // 28: geneza.v1.ArtifactChunk
	(*PublishArtifactResponse)(nil),  // 29: geneza.v1.PublishArtifactResponse
	(*SetDesiredVersionRequest)(nil), // 30: geneza.v1.SetDesiredVersionRequest
	(*FleetStatus)(nil),              // 31: geneza.v1.FleetStatus
	(*QueryAuditRequest)(nil),        // 32: geneza.v1.QueryAuditRequest
	(*AuditRecord)(nil),              // 33: geneza.v1.AuditRecord
	(*QueryAuditResponse)(nil),       // 34: geneza.v1.QueryAuditResponse
	(*Empty)(nil),                    // 35: geneza.v1.Empty
	nil,                              // 36: geneza.v1.EnrollRequest.LabelsEntry
	nil,                              // 37: geneza.v1.AgentHello.LabelsEntry
	nil,                              // 38: geneza.v1.NodeSummary.LabelsEntry
	nil,                              // 39: geneza.v1.CreateJoinTokenRequest.LabelsEntry
}
var file_geneza_v1_control_proto_depIdxs = []int32{
	36, // 0: geneza.v1.EnrollRequest.labels:type_name -> geneza.v1.EnrollRequest.LabelsEntry
	1,  // 1: geneza.v1.EnrollRequest.platform:type_name -> geneza.v1.PlatformInfo
	5,  // 2: geneza.v1.AgentMsg.hello:type_name -> geneza.v1.AgentHello
	6,  // 3: geneza.v1.AgentMsg.heartbeat:type_name -> geneza.v1.Heartbeat
	9,  // 4: geneza.v1.AgentMsg.session_event:type_name -> geneza.v1.SessionEvent
	8,  // 5: geneza.v1.AgentMsg.offer_ack:type_name -> geneza.v1.SessionOfferAck
	7,  // 6: geneza.v1.GatewayMsg.session_offer:type_name -> geneza.v1.SessionOffer
	14, // 7: geneza.v1.GatewayMsg.ping:type_name -> geneza.v1.Ping
	37, // 8: geneza.v1.AgentHello.labels:type_name -> geneza.v1.AgentHello.LabelsEntry
	38, // 9: geneza.v1.NodeSummary.labels:type_name -> geneza.v1.NodeSummary.LabelsEntry
	17, // 10: geneza.v1.ListNodesResponse.nodes:type_name -> geneza.v1.NodeSummary
	22, // 11: geneza.v1.ListSessionsResponse.sessions:type_name -> geneza.v1.SessionInfo
	39, // 12: geneza.v1.CreateJoinTokenRequest.labels:type_name -> geneza.v1.CreateJoinTokenRequest.LabelsEntry
	17, // 13: geneza.v1.FleetStatus.nodes:type_name -> geneza.v1.NodeSummary
	33, // 14: geneza.v1.QueryAuditResponse.records:type_name -> geneza.v1.AuditRecord
	0,  // 15: geneza.v1.Enrollment.Enroll:input_type -> geneza.v1.EnrollRequest
	3,  // 16: geneza.v1.NodeControl.Stream:input_type -> geneza.v1.AgentMsg
	12, // 17: geneza.v1.NodeControl.RenewCert:input_type -> geneza.v1.RenewCertRequest
	10, // 18: geneza.v1.NodeControl.UploadRecording:input_type -> geneza.v1.RecordingChunk
	15, // 19: geneza.v1.UserAPI.Login:input_type -> geneza.v1.LoginRequest
	18, // 20: geneza.v1.UserAPI.ListNodes:input_type -> geneza.v1.ListNodesRequest
	20, // 21: geneza.v1.UserAPI.CreateSession:input_type -> geneza.v1.CreateSessionRequest
	23, // 22: geneza.v1.UserAPI.ListSessions:input_type -> geneza.v1.ListSessionsRequest
	35, // 23: geneza.v1.UserAPI.WhoAmI:input_type -> geneza.v1.Empty
	26, // 24: geneza.v1.AdminAPI.CreateJoinToken:input_type -> geneza.v1.CreateJoinTokenRequest
	28, // 25: geneza.v1.AdminAPI.PublishArtifact:input_type -> geneza.v1.ArtifactChunk
	30, // 26: geneza.v1.AdminAPI.SetDesiredVersion:input_type -> geneza.v1.SetDesiredVersionRequest
	35, // 27: geneza.v1.AdminAPI.GetFleetStatus:input_type -> geneza.v1.Empty
	35, // 28: geneza.v1.AdminAPI.ReloadPolicy:input_type -> geneza.v1.Empty
	32, // 29: geneza.v1.AdminAPI.QueryAudit:input_type -> geneza.v1.QueryAuditRequest
	2,  // 30: geneza.v1.Enrollment.Enroll:output_type -> geneza.v1.EnrollResponse
	4,  // 31: geneza.v1.NodeControl.Stream:output_type -> geneza.v1.GatewayMsg
	13, // 32: geneza.v1.NodeControl.RenewCert:output_type -> geneza.v1.RenewCertResponse
	11, // 33: geneza.v1.NodeControl.UploadRecording:output_type -> geneza.v1.UploadAck
	16, // 34: geneza.v1.UserAPI.Login:output_type -> geneza.v1.LoginResponse
	19, // 35: geneza.v1.UserAPI.ListNodes:output_type -> geneza.v1.ListNodesResponse
	21, // 36: geneza.v1.UserAPI.CreateSession:output_type -> geneza.v1.CreateSessionResponse
	24, // 37: geneza.v1.UserAPI.ListSessions:output_type -> geneza.v1.ListSessionsResponse
	25, // 38: geneza.v1.UserAPI.WhoAmI:output_type -> geneza.v1.WhoAmIResponse
	27, // 39: geneza.v1.AdminAPI.CreateJoinToken:output_type -> geneza.v1.CreateJoinTokenResponse
	29, // 40: geneza.v1.AdminAPI.PublishArtifact:output_type -> geneza.v1.PublishArtifactResponse
	35, // 41: geneza.v1.AdminAPI.SetDesiredVersion:output_type -> geneza.v1.Empty
	31, // 42: geneza.v1.AdminAPI.GetFleetStatus:output_type -> geneza.v1.FleetStatus
	35, // 43: geneza.v1.AdminAPI.ReloadPolicy:output_type -> geneza.v1.Empty
	34, // 44: geneza.v1.AdminAPI.QueryAudit:output_type -> geneza.v1.QueryAuditResponse
	30, // [30:45] is the sub-list for method output_type
	15, // [15:30] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_geneza_v1_control_proto_init() }
func file_geneza_v1_control_proto_init() {
	if File_geneza_v1_control_proto != nil {
		return
	}
	file_geneza_v1_control_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentMsg_Hello)(nil),
		(*AgentMsg_Heartbeat)(nil),
		(*AgentMsg_SessionEvent)(nil),
		(*AgentMsg_OfferAck)(nil),
	}
	file_geneza_v1_control_proto_msgTypes[4].OneofWrappers = []any{
		(*GatewayMsg_SessionOffer)(nil),
		(*GatewayMsg_ClusterConfig)(nil),
		(*GatewayMsg_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geneza_v1_control_proto_rawDesc), len(file_geneza_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_geneza_v1_control_proto_goTypes,
		DependencyIndexes: file_geneza_v1_control_proto_depIdxs,
		MessageInfos:      file_geneza_v1_control_proto_msgTypes,
	}.Build()
	File_geneza_v1_control_proto = out.File
	file_geneza_v1_control_proto_goTypes = nil
	file_geneza_v1_control_proto_depIdxs = nil
}
