// Geneza control-plane API (gateway gRPC over mTLS).
//
// Three trust levels share one listener:
//   - Enrollment: no client cert (one-time token / provider document).
//   - UserAPI.Login: no client cert (OIDC token or local credentials).
//   - NodeControl: node mTLS cert required (URI geneza://node/<id>).
//   - UserAPI (rest) / AdminAPI: user mTLS cert required (URI geneza://user/<name>).
// Enforcement is per-RPC in the gateway auth interceptor.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: geneza/v1/control.proto

package genezav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Enrollment_Enroll_FullMethodName = "/geneza.v1.Enrollment/Enroll"
)

// EnrollmentClient is the client API for Enrollment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnrollmentClient interface {
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type enrollmentClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentClient(cc grpc.ClientConnInterface) EnrollmentClient {
	return &enrollmentClient{cc}
}

func (c *enrollmentClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, Enrollment_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentServer is the server API for Enrollment service.
// All implementations must embed UnimplementedEnrollmentServer
// for forward compatibility.
type EnrollmentServer interface {
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedEnrollmentServer()
}

// UnimplementedEnrollmentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrollmentServer struct{}

func (UnimplementedEnrollmentServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedEnrollmentServer) mustEmbedUnimplementedEnrollmentServer() {}
func (UnimplementedEnrollmentServer) testEmbeddedByValue()                    {}

// UnsafeEnrollmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentServer will
// result in compilation errors.
type UnsafeEnrollmentServer interface {
	mustEmbedUnimplementedEnrollmentServer()
}

func RegisterEnrollmentServer(s grpc.ServiceRegistrar, srv EnrollmentServer) {
	// If the following call panics, it indicates UnimplementedEnrollmentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Enrollment_ServiceDesc, srv)
}

func _Enrollment_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enrollment_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Enrollment_ServiceDesc is the grpc.ServiceDesc for Enrollment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Enrollment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geneza.v1.Enrollment",
	HandlerType: (*EnrollmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _Enrollment_Enroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geneza/v1/control.proto",
}

const (
	NodeControl_Stream_FullMethodName          = "/geneza.v1.NodeControl/Stream"
	NodeControl_RenewCert_FullMethodName       = "/geneza.v1.NodeControl/RenewCert"
	NodeControl_UploadRecording_FullMethodName = "/geneza.v1.NodeControl/UploadRecording"
)

// NodeControlClient is the client API for NodeControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeControlClient interface {
	// Persistent bidirectional control channel. First AgentMsg MUST be hello.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMsg, GatewayMsg], error)
	RenewCert(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error)
	// Upload an asciicast v2 session recording (recorded at the agent).
	UploadRecording(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RecordingChunk, UploadAck], error)
}

type nodeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControlClient(cc grpc.ClientConnInterface) NodeControlClient {
	return &nodeControlClient{cc}
}

func (c *nodeControlClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMsg, GatewayMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeControl_ServiceDesc.Streams[0], NodeControl_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMsg, GatewayMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_StreamClient = grpc.BidiStreamingClient[AgentMsg, GatewayMsg]

func (c *nodeControlClient) RenewCert(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewCertResponse)
	err := c.cc.Invoke(ctx, NodeControl_RenewCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) UploadRecording(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RecordingChunk, UploadAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeControl_ServiceDesc.Streams[1], NodeControl_UploadRecording_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RecordingChunk, UploadAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_UploadRecordingClient = grpc.ClientStreamingClient[RecordingChunk, UploadAck]

// NodeControlServer is the server API for NodeControl service.
// All implementations must embed UnimplementedNodeControlServer
// for forward compatibility.
type NodeControlServer interface {
	// Persistent bidirectional control channel. First AgentMsg MUST be hello.
	Stream(grpc.BidiStreamingServer[AgentMsg, GatewayMsg]) error
	RenewCert(context.Context, *RenewCertRequest) (*RenewCertResponse, error)
	// Upload an asciicast v2 session recording (recorded at the agent).
	UploadRecording(grpc.ClientStreamingServer[RecordingChunk, UploadAck]) error
	mustEmbedUnimplementedNodeControlServer()
}

// UnimplementedNodeControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeControlServer struct{}

func (UnimplementedNodeControlServer) Stream(grpc.BidiStreamingServer[AgentMsg, GatewayMsg]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedNodeControlServer) RenewCert(context.Context, *RenewCertRequest) (*RenewCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCert not implemented")
}
func (UnimplementedNodeControlServer) UploadRecording(grpc.ClientStreamingServer[RecordingChunk, UploadAck]) error {
	return status.Error(codes.Unimplemented, "method UploadRecording not implemented")
}
func (UnimplementedNodeControlServer) mustEmbedUnimplementedNodeControlServer() {}
func (UnimplementedNodeControlServer) testEmbeddedByValue()                     {}

// UnsafeNodeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControlServer will
// result in compilation errors.
type UnsafeNodeControlServer interface {
	mustEmbedUnimplementedNodeControlServer()
}

func RegisterNodeControlServer(s grpc.ServiceRegistrar, srv NodeControlServer) {
	// If the following call panics, it indicates UnimplementedNodeControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeControl_ServiceDesc, srv)
}

func _NodeControl_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeControlServer).Stream(&grpc.GenericServerStream[AgentMsg, GatewayMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_StreamServer = grpc.BidiStreamingServer[AgentMsg, GatewayMsg]

func _NodeControl_RenewCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).RenewCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_RenewCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).RenewCert(ctx, req.(*RenewCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_UploadRecording_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeControlServer).UploadRecording(&grpc.GenericServerStream[RecordingChunk, UploadAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_UploadRecordingServer = grpc.ClientStreamingServer[RecordingChunk, UploadAck]

// NodeControl_ServiceDesc is the grpc.ServiceDesc for NodeControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geneza.v1.NodeControl",
	HandlerType: (*NodeControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenewCert",
			Handler:    _NodeControl_RenewCert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _NodeControl_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadRecording",
			Handler:       _NodeControl_UploadRecording_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "geneza/v1/control.proto",
}

const (
	UserAPI_Login_FullMethodName         = "/geneza.v1.UserAPI/Login"
	UserAPI_ListNodes_FullMethodName     = "/geneza.v1.UserAPI/ListNodes"
	UserAPI_ListServices_FullMethodName  = "/geneza.v1.UserAPI/ListServices"
	UserAPI_CreateSession_FullMethodName = "/geneza.v1.UserAPI/CreateSession"
	UserAPI_ListSessions_FullMethodName  = "/geneza.v1.UserAPI/ListSessions"
	UserAPI_WhoAmI_FullMethodName        = "/geneza.v1.UserAPI/WhoAmI"
)

// UserAPIClient is the client API for UserAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserAPIClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	WhoAmI(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WhoAmIResponse, error)
}

type userAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAPIClient(cc grpc.ClientConnInterface) UserAPIClient {
	return &userAPIClient{cc}
}

func (c *userAPIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, UserAPI_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAPIClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, UserAPI_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAPIClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, UserAPI_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAPIClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, UserAPI_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAPIClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, UserAPI_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAPIClient) WhoAmI(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, UserAPI_WhoAmI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAPIServer is the server API for UserAPI service.
// All implementations must embed UnimplementedUserAPIServer
// for forward compatibility.
type UserAPIServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	WhoAmI(context.Context, *Empty) (*WhoAmIResponse, error)
	mustEmbedUnimplementedUserAPIServer()
}

// UnimplementedUserAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserAPIServer struct{}

func (UnimplementedUserAPIServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserAPIServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedUserAPIServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedUserAPIServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedUserAPIServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedUserAPIServer) WhoAmI(context.Context, *Empty) (*WhoAmIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedUserAPIServer) mustEmbedUnimplementedUserAPIServer() {}
func (UnimplementedUserAPIServer) testEmbeddedByValue()                 {}

// UnsafeUserAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserAPIServer will
// result in compilation errors.
type UnsafeUserAPIServer interface {
	mustEmbedUnimplementedUserAPIServer()
}

func RegisterUserAPIServer(s grpc.ServiceRegistrar, srv UserAPIServer) {
	// If the following call panics, it indicates UnimplementedUserAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserAPI_ServiceDesc, srv)
}

func _UserAPI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAPI_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAPI_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAPI_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAPI_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAPI_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAPI_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAPI_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAPI_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAPI_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAPI_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAPIServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAPI_WhoAmI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAPIServer).WhoAmI(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// UserAPI_ServiceDesc is the grpc.ServiceDesc for UserAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geneza.v1.UserAPI",
	HandlerType: (*UserAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserAPI_Login_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _UserAPI_ListNodes_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _UserAPI_ListServices_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _UserAPI_CreateSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _UserAPI_ListSessions_Handler,
		},
		{
			MethodName: "WhoAmI",
			Handler:    _UserAPI_WhoAmI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geneza/v1/control.proto",
}

const (
	AdminAPI_CreateJoinToken_FullMethodName    = "/geneza.v1.AdminAPI/CreateJoinToken"
	AdminAPI_ApproveNode_FullMethodName        = "/geneza.v1.AdminAPI/ApproveNode"
	AdminAPI_ListWorkspaces_FullMethodName     = "/geneza.v1.AdminAPI/ListWorkspaces"
	AdminAPI_RemoveNode_FullMethodName         = "/geneza.v1.AdminAPI/RemoveNode"
	AdminAPI_PublishArtifact_FullMethodName    = "/geneza.v1.AdminAPI/PublishArtifact"
	AdminAPI_SetDesiredVersion_FullMethodName  = "/geneza.v1.AdminAPI/SetDesiredVersion"
	AdminAPI_GetFleetStatus_FullMethodName     = "/geneza.v1.AdminAPI/GetFleetStatus"
	AdminAPI_ReloadPolicy_FullMethodName       = "/geneza.v1.AdminAPI/ReloadPolicy"
	AdminAPI_QueryAudit_FullMethodName         = "/geneza.v1.AdminAPI/QueryAudit"
	AdminAPI_RevokeSession_FullMethodName      = "/geneza.v1.AdminAPI/RevokeSession"
	AdminAPI_RevokeUser_FullMethodName         = "/geneza.v1.AdminAPI/RevokeUser"
	AdminAPI_SetNodeModules_FullMethodName     = "/geneza.v1.AdminAPI/SetNodeModules"
	AdminAPI_GetNodeModules_FullMethodName     = "/geneza.v1.AdminAPI/GetNodeModules"
	AdminAPI_BindSource_FullMethodName         = "/geneza.v1.AdminAPI/BindSource"
	AdminAPI_UnbindSource_FullMethodName       = "/geneza.v1.AdminAPI/UnbindSource"
	AdminAPI_ListSourceBindings_FullMethodName = "/geneza.v1.AdminAPI/ListSourceBindings"
)

// AdminAPIClient is the client API for AdminAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminAPIClient interface {
	CreateJoinToken(ctx context.Context, in *CreateJoinTokenRequest, opts ...grpc.CallOption) (*CreateJoinTokenResponse, error)
	// ApproveNode flips a node's pending-approval gate (zero-trust admission
	// control): an unapproved node has an identity but no session can be brokered
	// to it until an admin approves. approve=false re-quarantines a node.
	ApproveNode(ctx context.Context, in *ApproveNodeRequest, opts ...grpc.CallOption) (*Empty, error)
	// ListWorkspaces lists the tenants this gateway hosts.
	ListWorkspaces(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListWorkspacesResponse, error)
	// RemoveNode decommissions a machine: deletes its record so it no longer
	// appears in the fleet and must re-enroll (and re-be-approved) to return.
	RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*Empty, error)
	PublishArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ArtifactChunk, PublishArtifactResponse], error)
	SetDesiredVersion(ctx context.Context, in *SetDesiredVersionRequest, opts ...grpc.CallOption) (*Empty, error)
	GetFleetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FleetStatus, error)
	ReloadPolicy(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (*QueryAuditResponse, error)
	// RevokeSession force-terminates a live session (admin "kick"). RevokeUser
	// revokes all of a user's sessions.
	RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*Empty, error)
	RevokeUser(ctx context.Context, in *RevokeUserRequest, opts ...grpc.CallOption) (*RevokeCountResponse, error)
	// Per-node agent modules (enable/disable monitoring & future exporters). The
	// gateway persists the desired set and pushes it to the node in realtime.
	SetNodeModules(ctx context.Context, in *SetNodeModulesRequest, opts ...grpc.CallOption) (*Empty, error)
	GetNodeModules(ctx context.Context, in *GetNodeModulesRequest, opts ...grpc.CallOption) (*NodeModulesResponse, error)
	// Cloud-qualified SOURCE bindings (workspace-as-hub, §6): bind an external
	// identity source (e.g. openstack:project:<svc>:<uuid>, idp:group:<realm>:<g>)
	// to a workspace so its VMs/users enroll/land there. Operator pre-bind path.
	BindSource(ctx context.Context, in *BindSourceRequest, opts ...grpc.CallOption) (*Empty, error)
	UnbindSource(ctx context.Context, in *UnbindSourceRequest, opts ...grpc.CallOption) (*Empty, error)
	ListSourceBindings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSourceBindingsResponse, error)
}

type adminAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminAPIClient(cc grpc.ClientConnInterface) AdminAPIClient {
	return &adminAPIClient{cc}
}

func (c *adminAPIClient) CreateJoinToken(ctx context.Context, in *CreateJoinTokenRequest, opts ...grpc.CallOption) (*CreateJoinTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJoinTokenResponse)
	err := c.cc.Invoke(ctx, AdminAPI_CreateJoinToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) ApproveNode(ctx context.Context, in *ApproveNodeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminAPI_ApproveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) ListWorkspaces(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListWorkspacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkspacesResponse)
	err := c.cc.Invoke(ctx, AdminAPI_ListWorkspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) RemoveNode(ctx context.Context, in *RemoveNodeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminAPI_RemoveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) PublishArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ArtifactChunk, PublishArtifactResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminAPI_ServiceDesc.Streams[0], AdminAPI_PublishArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArtifactChunk, PublishArtifactResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminAPI_PublishArtifactClient = grpc.ClientStreamingClient[ArtifactChunk, PublishArtifactResponse]

func (c *adminAPIClient) SetDesiredVersion(ctx context.Context, in *SetDesiredVersionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminAPI_SetDesiredVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) GetFleetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FleetStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FleetStatus)
	err := c.cc.Invoke(ctx, AdminAPI_GetFleetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) ReloadPolicy(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminAPI_ReloadPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) QueryAudit(ctx context.Context, in *QueryAuditRequest, opts ...grpc.CallOption) (*QueryAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAuditResponse)
	err := c.cc.Invoke(ctx, AdminAPI_QueryAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminAPI_RevokeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) RevokeUser(ctx context.Context, in *RevokeUserRequest, opts ...grpc.CallOption) (*RevokeCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCountResponse)
	err := c.cc.Invoke(ctx, AdminAPI_RevokeUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) SetNodeModules(ctx context.Context, in *SetNodeModulesRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminAPI_SetNodeModules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) GetNodeModules(ctx context.Context, in *GetNodeModulesRequest, opts ...grpc.CallOption) (*NodeModulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeModulesResponse)
	err := c.cc.Invoke(ctx, AdminAPI_GetNodeModules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) BindSource(ctx context.Context, in *BindSourceRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminAPI_BindSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) UnbindSource(ctx context.Context, in *UnbindSourceRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminAPI_UnbindSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAPIClient) ListSourceBindings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSourceBindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSourceBindingsResponse)
	err := c.cc.Invoke(ctx, AdminAPI_ListSourceBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminAPIServer is the server API for AdminAPI service.
// All implementations must embed UnimplementedAdminAPIServer
// for forward compatibility.
type AdminAPIServer interface {
	CreateJoinToken(context.Context, *CreateJoinTokenRequest) (*CreateJoinTokenResponse, error)
	// ApproveNode flips a node's pending-approval gate (zero-trust admission
	// control): an unapproved node has an identity but no session can be brokered
	// to it until an admin approves. approve=false re-quarantines a node.
	ApproveNode(context.Context, *ApproveNodeRequest) (*Empty, error)
	// ListWorkspaces lists the tenants this gateway hosts.
	ListWorkspaces(context.Context, *Empty) (*ListWorkspacesResponse, error)
	// RemoveNode decommissions a machine: deletes its record so it no longer
	// appears in the fleet and must re-enroll (and re-be-approved) to return.
	RemoveNode(context.Context, *RemoveNodeRequest) (*Empty, error)
	PublishArtifact(grpc.ClientStreamingServer[ArtifactChunk, PublishArtifactResponse]) error
	SetDesiredVersion(context.Context, *SetDesiredVersionRequest) (*Empty, error)
	GetFleetStatus(context.Context, *Empty) (*FleetStatus, error)
	ReloadPolicy(context.Context, *Empty) (*Empty, error)
	QueryAudit(context.Context, *QueryAuditRequest) (*QueryAuditResponse, error)
	// RevokeSession force-terminates a live session (admin "kick"). RevokeUser
	// revokes all of a user's sessions.
	RevokeSession(context.Context, *RevokeSessionRequest) (*Empty, error)
	RevokeUser(context.Context, *RevokeUserRequest) (*RevokeCountResponse, error)
	// Per-node agent modules (enable/disable monitoring & future exporters). The
	// gateway persists the desired set and pushes it to the node in realtime.
	SetNodeModules(context.Context, *SetNodeModulesRequest) (*Empty, error)
	GetNodeModules(context.Context, *GetNodeModulesRequest) (*NodeModulesResponse, error)
	// Cloud-qualified SOURCE bindings (workspace-as-hub, §6): bind an external
	// identity source (e.g. openstack:project:<svc>:<uuid>, idp:group:<realm>:<g>)
	// to a workspace so its VMs/users enroll/land there. Operator pre-bind path.
	BindSource(context.Context, *BindSourceRequest) (*Empty, error)
	UnbindSource(context.Context, *UnbindSourceRequest) (*Empty, error)
	ListSourceBindings(context.Context, *Empty) (*ListSourceBindingsResponse, error)
	mustEmbedUnimplementedAdminAPIServer()
}

// UnimplementedAdminAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminAPIServer struct{}

func (UnimplementedAdminAPIServer) CreateJoinToken(context.Context, *CreateJoinTokenRequest) (*CreateJoinTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJoinToken not implemented")
}
func (UnimplementedAdminAPIServer) ApproveNode(context.Context, *ApproveNodeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveNode not implemented")
}
func (UnimplementedAdminAPIServer) ListWorkspaces(context.Context, *Empty) (*ListWorkspacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedAdminAPIServer) RemoveNode(context.Context, *RemoveNodeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveNode not implemented")
}
func (UnimplementedAdminAPIServer) PublishArtifact(grpc.ClientStreamingServer[ArtifactChunk, PublishArtifactResponse]) error {
	return status.Error(codes.Unimplemented, "method PublishArtifact not implemented")
}
func (UnimplementedAdminAPIServer) SetDesiredVersion(context.Context, *SetDesiredVersionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDesiredVersion not implemented")
}
func (UnimplementedAdminAPIServer) GetFleetStatus(context.Context, *Empty) (*FleetStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFleetStatus not implemented")
}
func (UnimplementedAdminAPIServer) ReloadPolicy(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadPolicy not implemented")
}
func (UnimplementedAdminAPIServer) QueryAudit(context.Context, *QueryAuditRequest) (*QueryAuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryAudit not implemented")
}
func (UnimplementedAdminAPIServer) RevokeSession(context.Context, *RevokeSessionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeSession not implemented")
}
func (UnimplementedAdminAPIServer) RevokeUser(context.Context, *RevokeUserRequest) (*RevokeCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeUser not implemented")
}
func (UnimplementedAdminAPIServer) SetNodeModules(context.Context, *SetNodeModulesRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNodeModules not implemented")
}
func (UnimplementedAdminAPIServer) GetNodeModules(context.Context, *GetNodeModulesRequest) (*NodeModulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeModules not implemented")
}
func (UnimplementedAdminAPIServer) BindSource(context.Context, *BindSourceRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BindSource not implemented")
}
func (UnimplementedAdminAPIServer) UnbindSource(context.Context, *UnbindSourceRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindSource not implemented")
}
func (UnimplementedAdminAPIServer) ListSourceBindings(context.Context, *Empty) (*ListSourceBindingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSourceBindings not implemented")
}
func (UnimplementedAdminAPIServer) mustEmbedUnimplementedAdminAPIServer() {}
func (UnimplementedAdminAPIServer) testEmbeddedByValue()                  {}

// UnsafeAdminAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminAPIServer will
// result in compilation errors.
type UnsafeAdminAPIServer interface {
	mustEmbedUnimplementedAdminAPIServer()
}

func RegisterAdminAPIServer(s grpc.ServiceRegistrar, srv AdminAPIServer) {
	// If the following call panics, it indicates UnimplementedAdminAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminAPI_ServiceDesc, srv)
}

func _AdminAPI_CreateJoinToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJoinTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).CreateJoinToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_CreateJoinToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).CreateJoinToken(ctx, req.(*CreateJoinTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_ApproveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).ApproveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_ApproveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).ApproveNode(ctx, req.(*ApproveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_ListWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).ListWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_ListWorkspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).ListWorkspaces(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_RemoveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).RemoveNode(ctx, req.(*RemoveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_PublishArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdminAPIServer).PublishArtifact(&grpc.GenericServerStream[ArtifactChunk, PublishArtifactResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminAPI_PublishArtifactServer = grpc.ClientStreamingServer[ArtifactChunk, PublishArtifactResponse]

func _AdminAPI_SetDesiredVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDesiredVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).SetDesiredVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_SetDesiredVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).SetDesiredVersion(ctx, req.(*SetDesiredVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_GetFleetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).GetFleetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_GetFleetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).GetFleetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_ReloadPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).ReloadPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_ReloadPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).ReloadPolicy(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_QueryAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).QueryAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_QueryAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).QueryAudit(ctx, req.(*QueryAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_RevokeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).RevokeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_RevokeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).RevokeSession(ctx, req.(*RevokeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_RevokeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).RevokeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_RevokeUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).RevokeUser(ctx, req.(*RevokeUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_SetNodeModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNodeModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).SetNodeModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_SetNodeModules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).SetNodeModules(ctx, req.(*SetNodeModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_GetNodeModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).GetNodeModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_GetNodeModules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).GetNodeModules(ctx, req.(*GetNodeModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_BindSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).BindSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_BindSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).BindSource(ctx, req.(*BindSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_UnbindSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).UnbindSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_UnbindSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).UnbindSource(ctx, req.(*UnbindSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAPI_ListSourceBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServer).ListSourceBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAPI_ListSourceBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServer).ListSourceBindings(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminAPI_ServiceDesc is the grpc.ServiceDesc for AdminAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geneza.v1.AdminAPI",
	HandlerType: (*AdminAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJoinToken",
			Handler:    _AdminAPI_CreateJoinToken_Handler,
		},
		{
			MethodName: "ApproveNode",
			Handler:    _AdminAPI_ApproveNode_Handler,
		},
		{
			MethodName: "ListWorkspaces",
			Handler:    _AdminAPI_ListWorkspaces_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _AdminAPI_RemoveNode_Handler,
		},
		{
			MethodName: "SetDesiredVersion",
			Handler:    _AdminAPI_SetDesiredVersion_Handler,
		},
		{
			MethodName: "GetFleetStatus",
			Handler:    _AdminAPI_GetFleetStatus_Handler,
		},
		{
			MethodName: "ReloadPolicy",
			Handler:    _AdminAPI_ReloadPolicy_Handler,
		},
		{
			MethodName: "QueryAudit",
			Handler:    _AdminAPI_QueryAudit_Handler,
		},
		{
			MethodName: "RevokeSession",
			Handler:    _AdminAPI_RevokeSession_Handler,
		},
		{
			MethodName: "RevokeUser",
			Handler:    _AdminAPI_RevokeUser_Handler,
		},
		{
			MethodName: "SetNodeModules",
			Handler:    _AdminAPI_SetNodeModules_Handler,
		},
		{
			MethodName: "GetNodeModules",
			Handler:    _AdminAPI_GetNodeModules_Handler,
		},
		{
			MethodName: "BindSource",
			Handler:    _AdminAPI_BindSource_Handler,
		},
		{
			MethodName: "UnbindSource",
			Handler:    _AdminAPI_UnbindSource_Handler,
		},
		{
			MethodName: "ListSourceBindings",
			Handler:    _AdminAPI_ListSourceBindings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishArtifact",
			Handler:       _AdminAPI_PublishArtifact_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "geneza/v1/control.proto",
}
