// Agent-internal session host API (gRPC over a unix socket).
//
// The session host is a small, stable, separately-supervised process that
// owns live PTYs and their buffers so that worker restarts (binary updates)
// never kill live sessions. The worker bridges tunnel channels to this API.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: geneza/v1/sessionhost.proto

package genezav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // gateway session id (for audit correlation)
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`                            // geneza user identity (audit)
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                        // shell|exec
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`                      // empty = login shell
	Pty           bool                   `protobuf:"varint,5,opt,name=pty,proto3" json:"pty,omitempty"`
	Cols          uint32                 `protobuf:"varint,6,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,7,opt,name=rows,proto3" json:"rows,omitempty"`
	Env           map[string]string      `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Detachable    bool                   `protobuf:"varint,9,opt,name=detachable,proto3" json:"detachable,omitempty"`
	Record        bool                   `protobuf:"varint,10,opt,name=record,proto3" json:"record,omitempty"`              // write asciicast v2 to the spool dir
	OsUser        string                 `protobuf:"bytes,11,opt,name=os_user,json=osUser,proto3" json:"os_user,omitempty"` // OS account to run as (v1: agent's own user)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostCreateRequest) Reset() {
	*x = HostCreateRequest{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCreateRequest) ProtoMessage() {}

func (x *HostCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCreateRequest.ProtoReflect.Descriptor instead.
func (*HostCreateRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{0}
}

func (x *HostCreateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HostCreateRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *HostCreateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *HostCreateRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *HostCreateRequest) GetPty() bool {
	if x != nil {
		return x.Pty
	}
	return false
}

func (x *HostCreateRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *HostCreateRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *HostCreateRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *HostCreateRequest) GetDetachable() bool {
	if x != nil {
		return x.Detachable
	}
	return false
}

func (x *HostCreateRequest) GetRecord() bool {
	if x != nil {
		return x.Record
	}
	return false
}

func (x *HostCreateRequest) GetOsUser() string {
	if x != nil {
		return x.OsUser
	}
	return ""
}

type HostCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostSessionId string                 `protobuf:"bytes,1,opt,name=host_session_id,json=hostSessionId,proto3" json:"host_session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostCreateResponse) Reset() {
	*x = HostCreateResponse{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCreateResponse) ProtoMessage() {}

func (x *HostCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCreateResponse.ProtoReflect.Descriptor instead.
func (*HostCreateResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{1}
}

func (x *HostCreateResponse) GetHostSessionId() string {
	if x != nil {
		return x.HostSessionId
	}
	return ""
}

type ClientToHost struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientToHost_Open
	//	*ClientToHost_Input
	//	*ClientToHost_Resize
	//	*ClientToHost_Signal
	//	*ClientToHost_Detach
	//	*ClientToHost_StdinEof
	Msg           isClientToHost_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToHost) Reset() {
	*x = ClientToHost{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToHost) ProtoMessage() {}

func (x *ClientToHost) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToHost.ProtoReflect.Descriptor instead.
func (*ClientToHost) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{2}
}

func (x *ClientToHost) GetMsg() isClientToHost_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientToHost) GetOpen() *AttachOpen {
	if x != nil {
		if x, ok := x.Msg.(*ClientToHost_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *ClientToHost) GetInput() *Input {
	if x != nil {
		if x, ok := x.Msg.(*ClientToHost_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *ClientToHost) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Msg.(*ClientToHost_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ClientToHost) GetSignal() *Signal {
	if x != nil {
		if x, ok := x.Msg.(*ClientToHost_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *ClientToHost) GetDetach() *Detach {
	if x != nil {
		if x, ok := x.Msg.(*ClientToHost_Detach); ok {
			return x.Detach
		}
	}
	return nil
}

func (x *ClientToHost) GetStdinEof() *Stdin_EOF {
	if x != nil {
		if x, ok := x.Msg.(*ClientToHost_StdinEof); ok {
			return x.StdinEof
		}
	}
	return nil
}

type isClientToHost_Msg interface {
	isClientToHost_Msg()
}

type ClientToHost_Open struct {
	Open *AttachOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type ClientToHost_Input struct {
	Input *Input `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type ClientToHost_Resize struct {
	Resize *Resize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

type ClientToHost_Signal struct {
	Signal *Signal `protobuf:"bytes,4,opt,name=signal,proto3,oneof"`
}

type ClientToHost_Detach struct {
	Detach *Detach `protobuf:"bytes,5,opt,name=detach,proto3,oneof"`
}

type ClientToHost_StdinEof struct {
	StdinEof *Stdin_EOF `protobuf:"bytes,6,opt,name=stdin_eof,json=stdinEof,proto3,oneof"`
}

func (*ClientToHost_Open) isClientToHost_Msg() {}

func (*ClientToHost_Input) isClientToHost_Msg() {}

func (*ClientToHost_Resize) isClientToHost_Msg() {}

func (*ClientToHost_Signal) isClientToHost_Msg() {}

func (*ClientToHost_Detach) isClientToHost_Msg() {}

func (*ClientToHost_StdinEof) isClientToHost_Msg() {}

type AttachOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostSessionId string                 `protobuf:"bytes,1,opt,name=host_session_id,json=hostSessionId,proto3" json:"host_session_id,omitempty"`
	// Last output seq the client has rendered. 0 = fresh attach (full snapshot).
	LastSeenSeq   uint64 `protobuf:"varint,2,opt,name=last_seen_seq,json=lastSeenSeq,proto3" json:"last_seen_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachOpen) Reset() {
	*x = AttachOpen{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachOpen) ProtoMessage() {}

func (x *AttachOpen) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachOpen.ProtoReflect.Descriptor instead.
func (*AttachOpen) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{3}
}

func (x *AttachOpen) GetHostSessionId() string {
	if x != nil {
		return x.HostSessionId
	}
	return ""
}

func (x *AttachOpen) GetLastSeenSeq() uint64 {
	if x != nil {
		return x.LastSeenSeq
	}
	return 0
}

// Input is sequence-numbered so a reconnecting client never double-applies
// or drops keystrokes: the host ignores any input with seq <= last applied.
type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{4}
}

func (x *Input) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Input) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{5}
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type Signal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // INT, TERM, HUP, ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{6}
}

func (x *Signal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Detach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detach) Reset() {
	*x = Detach{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detach) ProtoMessage() {}

func (x *Detach) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detach.ProtoReflect.Descriptor instead.
func (*Detach) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{7}
}

type Stdin_EOF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stdin_EOF) Reset() {
	*x = Stdin_EOF{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stdin_EOF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stdin_EOF) ProtoMessage() {}

func (x *Stdin_EOF) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stdin_EOF.ProtoReflect.Descriptor instead.
func (*Stdin_EOF) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{8}
}

type HostToClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*HostToClient_Snapshot
	//	*HostToClient_Output
	//	*HostToClient_Stderr
	//	*HostToClient_Exit
	//	*HostToClient_InputAck
	Msg           isHostToClient_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostToClient) Reset() {
	*x = HostToClient{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostToClient) ProtoMessage() {}

func (x *HostToClient) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostToClient.ProtoReflect.Descriptor instead.
func (*HostToClient) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{9}
}

func (x *HostToClient) GetMsg() isHostToClient_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *HostToClient) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Msg.(*HostToClient_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *HostToClient) GetOutput() *Output {
	if x != nil {
		if x, ok := x.Msg.(*HostToClient_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *HostToClient) GetStderr() *Stderr {
	if x != nil {
		if x, ok := x.Msg.(*HostToClient_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *HostToClient) GetExit() *Exit {
	if x != nil {
		if x, ok := x.Msg.(*HostToClient_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *HostToClient) GetInputAck() *InputAck {
	if x != nil {
		if x, ok := x.Msg.(*HostToClient_InputAck); ok {
			return x.InputAck
		}
	}
	return nil
}

type isHostToClient_Msg interface {
	isHostToClient_Msg()
}

type HostToClient_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type HostToClient_Output struct {
	Output *Output `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type HostToClient_Stderr struct {
	Stderr *Stderr `protobuf:"bytes,3,opt,name=stderr,proto3,oneof"`
}

type HostToClient_Exit struct {
	Exit *Exit `protobuf:"bytes,4,opt,name=exit,proto3,oneof"`
}

type HostToClient_InputAck struct {
	InputAck *InputAck `protobuf:"bytes,5,opt,name=input_ack,json=inputAck,proto3,oneof"`
}

func (*HostToClient_Snapshot) isHostToClient_Msg() {}

func (*HostToClient_Output) isHostToClient_Msg() {}

func (*HostToClient_Stderr) isHostToClient_Msg() {}

func (*HostToClient_Exit) isHostToClient_Msg() {}

func (*HostToClient_InputAck) isHostToClient_Msg() {}

// Snapshot carries an ANSI repaint of the current screen (vt10x render) and
// the output seq it is consistent with; subsequent Output frames continue
// from seq+1. cols/rows are the session's current size.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{10}
}

func (x *Snapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Snapshot) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Snapshot) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Snapshot) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{11}
}

func (x *Output) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Output) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Stderr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stderr) Reset() {
	*x = Stderr{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stderr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stderr) ProtoMessage() {}

func (x *Stderr) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stderr.ProtoReflect.Descriptor instead.
func (*Stderr) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{12}
}

func (x *Stderr) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Stderr) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Exit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // "exited" | "signaled:<sig>" | "killed" | "reaped"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exit) Reset() {
	*x = Exit{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exit) ProtoMessage() {}

func (x *Exit) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exit.ProtoReflect.Descriptor instead.
func (*Exit) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{13}
}

func (x *Exit) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Exit) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type InputAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputAck) Reset() {
	*x = InputAck{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputAck) ProtoMessage() {}

func (x *InputAck) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputAck.ProtoReflect.Descriptor instead.
func (*InputAck) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{14}
}

func (x *InputAck) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type HostSessionInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HostSessionId    string                 `protobuf:"bytes,1,opt,name=host_session_id,json=hostSessionId,proto3" json:"host_session_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	User             string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Action           string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	State            string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"` // attached|detached|exited
	Detachable       bool                   `protobuf:"varint,6,opt,name=detachable,proto3" json:"detachable,omitempty"`
	StartedUnix      int64                  `protobuf:"varint,7,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`
	LastActivityUnix int64                  `protobuf:"varint,8,opt,name=last_activity_unix,json=lastActivityUnix,proto3" json:"last_activity_unix,omitempty"`
	Cols             uint32                 `protobuf:"varint,9,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows             uint32                 `protobuf:"varint,10,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HostSessionInfo) Reset() {
	*x = HostSessionInfo{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSessionInfo) ProtoMessage() {}

func (x *HostSessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSessionInfo.ProtoReflect.Descriptor instead.
func (*HostSessionInfo) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{15}
}

func (x *HostSessionInfo) GetHostSessionId() string {
	if x != nil {
		return x.HostSessionId
	}
	return ""
}

func (x *HostSessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HostSessionInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *HostSessionInfo) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *HostSessionInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HostSessionInfo) GetDetachable() bool {
	if x != nil {
		return x.Detachable
	}
	return false
}

func (x *HostSessionInfo) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *HostSessionInfo) GetLastActivityUnix() int64 {
	if x != nil {
		return x.LastActivityUnix
	}
	return 0
}

func (x *HostSessionInfo) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *HostSessionInfo) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type HostListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostListRequest) Reset() {
	*x = HostListRequest{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostListRequest) ProtoMessage() {}

func (x *HostListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostListRequest.ProtoReflect.Descriptor instead.
func (*HostListRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{16}
}

type HostListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*HostSessionInfo     `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostListResponse) Reset() {
	*x = HostListResponse{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostListResponse) ProtoMessage() {}

func (x *HostListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostListResponse.ProtoReflect.Descriptor instead.
func (*HostListResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{17}
}

func (x *HostListResponse) GetSessions() []*HostSessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type HostKillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostSessionId string                 `protobuf:"bytes,1,opt,name=host_session_id,json=hostSessionId,proto3" json:"host_session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostKillRequest) Reset() {
	*x = HostKillRequest{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostKillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostKillRequest) ProtoMessage() {}

func (x *HostKillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostKillRequest.ProtoReflect.Descriptor instead.
func (*HostKillRequest) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{18}
}

func (x *HostKillRequest) GetHostSessionId() string {
	if x != nil {
		return x.HostSessionId
	}
	return ""
}

type HostHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Active        uint32                 `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Detached      uint32                 `protobuf:"varint,3,opt,name=detached,proto3" json:"detached,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostHealthResponse) Reset() {
	*x = HostHealthResponse{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostHealthResponse) ProtoMessage() {}

func (x *HostHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostHealthResponse.ProtoReflect.Descriptor instead.
func (*HostHealthResponse) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{19}
}

func (x *HostHealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HostHealthResponse) GetActive() uint32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *HostHealthResponse) GetDetached() uint32 {
	if x != nil {
		return x.Detached
	}
	return 0
}

func (x *HostHealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HostPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ForbidDetach    bool                   `protobuf:"varint,1,opt,name=forbid_detach,json=forbidDetach,proto3" json:"forbid_detach,omitempty"`
	MaxSessions     uint32                 `protobuf:"varint,2,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	MaxDetached     uint32                 `protobuf:"varint,3,opt,name=max_detached,json=maxDetached,proto3" json:"max_detached,omitempty"`
	RingBufferBytes uint32                 `protobuf:"varint,4,opt,name=ring_buffer_bytes,json=ringBufferBytes,proto3" json:"ring_buffer_bytes,omitempty"`
	DetachedTtlSec  uint32                 `protobuf:"varint,5,opt,name=detached_ttl_sec,json=detachedTtlSec,proto3" json:"detached_ttl_sec,omitempty"`
	IdleReapSec     uint32                 `protobuf:"varint,6,opt,name=idle_reap_sec,json=idleReapSec,proto3" json:"idle_reap_sec,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HostPolicy) Reset() {
	*x = HostPolicy{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostPolicy) ProtoMessage() {}

func (x *HostPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostPolicy.ProtoReflect.Descriptor instead.
func (*HostPolicy) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{20}
}

func (x *HostPolicy) GetForbidDetach() bool {
	if x != nil {
		return x.ForbidDetach
	}
	return false
}

func (x *HostPolicy) GetMaxSessions() uint32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *HostPolicy) GetMaxDetached() uint32 {
	if x != nil {
		return x.MaxDetached
	}
	return 0
}

func (x *HostPolicy) GetRingBufferBytes() uint32 {
	if x != nil {
		return x.RingBufferBytes
	}
	return 0
}

func (x *HostPolicy) GetDetachedTtlSec() uint32 {
	if x != nil {
		return x.DetachedTtlSec
	}
	return 0
}

func (x *HostPolicy) GetIdleReapSec() uint32 {
	if x != nil {
		return x.IdleReapSec
	}
	return 0
}

type HostEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostEmpty) Reset() {
	*x = HostEmpty{}
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostEmpty) ProtoMessage() {}

func (x *HostEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_geneza_v1_sessionhost_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostEmpty.ProtoReflect.Descriptor instead.
func (*HostEmpty) Descriptor() ([]byte, []int) {
	return file_geneza_v1_sessionhost_proto_rawDescGZIP(), []int{21}
}

var File_geneza_v1_sessionhost_proto protoreflect.FileDescriptor

const file_geneza_v1_sessionhost_proto_rawDesc = "" +
	"\n" +
	"\x1bgeneza/v1/sessionhost.proto\x12\tgeneza.v1\"\xf4\x02\n" +
	"\x11HostCreateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x10\n" +
	"\x03pty\x18\x05 \x01(\bR\x03pty\x12\x12\n" +
	"\x04cols\x18\x06 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\a \x01(\rR\x04rows\x127\n" +
	"\x03env\x18\b \x03(\v2%.geneza.v1.HostCreateRequest.EnvEntryR\x03env\x12\x1e\n" +
	"\n" +
	"detachable\x18\t \x01(\bR\n" +
	"detachable\x12\x16\n" +
	"\x06record\x18\n" +
	" \x01(\bR\x06record\x12\x17\n" +
	"\aos_user\x18\v \x01(\tR\x06osUser\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x12HostCreateResponse\x12&\n" +
	"\x0fhost_session_id\x18\x01 \x01(\tR\rhostSessionId\"\xa8\x02\n" +
	"\fClientToHost\x12+\n" +
	"\x04open\x18\x01 \x01(\v2\x15.geneza.v1.AttachOpenH\x00R\x04open\x12(\n" +
	"\x05input\x18\x02 \x01(\v2\x10.geneza.v1.InputH\x00R\x05input\x12+\n" +
	"\x06resize\x18\x03 \x01(\v2\x11.geneza.v1.ResizeH\x00R\x06resize\x12+\n" +
	"\x06signal\x18\x04 \x01(\v2\x11.geneza.v1.SignalH\x00R\x06signal\x12+\n" +
	"\x06detach\x18\x05 \x01(\v2\x11.geneza.v1.DetachH\x00R\x06detach\x123\n" +
	"\tstdin_eof\x18\x06 \x01(\v2\x14.geneza.v1.Stdin_EOFH\x00R\bstdinEofB\x05\n" +
	"\x03msg\"X\n" +
	"\n" +
	"AttachOpen\x12&\n" +
	"\x0fhost_session_id\x18\x01 \x01(\tR\rhostSessionId\x12\"\n" +
	"\rlast_seen_seq\x18\x02 \x01(\x04R\vlastSeenSeq\"-\n" +
	"\x05Input\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"0\n" +
	"\x06Resize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x1c\n" +
	"\x06Signal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\b\n" +
	"\x06Detach\"\v\n" +
	"\tStdin_EOF\"\xfd\x01\n" +
	"\fHostToClient\x121\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x13.geneza.v1.SnapshotH\x00R\bsnapshot\x12+\n" +
	"\x06output\x18\x02 \x01(\v2\x11.geneza.v1.OutputH\x00R\x06output\x12+\n" +
	"\x06stderr\x18\x03 \x01(\v2\x11.geneza.v1.StderrH\x00R\x06stderr\x12%\n" +
	"\x04exit\x18\x04 \x01(\v2\x0f.geneza.v1.ExitH\x00R\x04exit\x122\n" +
	"\tinput_ack\x18\x05 \x01(\v2\x13.geneza.v1.InputAckH\x00R\binputAckB\x05\n" +
	"\x03msg\"X\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\".\n" +
	"\x06Output\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\".\n" +
	"\x06Stderr\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"2\n" +
	"\x04Exit\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x1c\n" +
	"\bInputAck\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"\xb3\x02\n" +
	"\x0fHostSessionInfo\x12&\n" +
	"\x0fhost_session_id\x18\x01 \x01(\tR\rhostSessionId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1e\n" +
	"\n" +
	"detachable\x18\x06 \x01(\bR\n" +
	"detachable\x12!\n" +
	"\fstarted_unix\x18\a \x01(\x03R\vstartedUnix\x12,\n" +
	"\x12last_activity_unix\x18\b \x01(\x03R\x10lastActivityUnix\x12\x12\n" +
	"\x04cols\x18\t \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\n" +
	" \x01(\rR\x04rows\"\x11\n" +
	"\x0fHostListRequest\"J\n" +
	"\x10HostListResponse\x126\n" +
	"\bsessions\x18\x01 \x03(\v2\x1a.geneza.v1.HostSessionInfoR\bsessions\"9\n" +
	"\x0fHostKillRequest\x12&\n" +
	"\x0fhost_session_id\x18\x01 \x01(\tR\rhostSessionId\"r\n" +
	"\x12HostHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06active\x18\x02 \x01(\rR\x06active\x12\x1a\n" +
	"\bdetached\x18\x03 \x01(\rR\bdetached\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xf1\x01\n" +
	"\n" +
	"HostPolicy\x12#\n" +
	"\rforbid_detach\x18\x01 \x01(\bR\fforbidDetach\x12!\n" +
	"\fmax_sessions\x18\x02 \x01(\rR\vmaxSessions\x12!\n" +
	"\fmax_detached\x18\x03 \x01(\rR\vmaxDetached\x12*\n" +
	"\x11ring_buffer_bytes\x18\x04 \x01(\rR\x0fringBufferBytes\x12(\n" +
	"\x10detached_ttl_sec\x18\x05 \x01(\rR\x0edetachedTtlSec\x12\"\n" +
	"\ridle_reap_sec\x18\x06 \x01(\rR\vidleReapSec\"\v\n" +
	"\tHostEmpty2\x8a\x03\n" +
	"\vSessionHost\x12E\n" +
	"\x06Create\x12\x1c.geneza.v1.HostCreateRequest\x1a\x1d.geneza.v1.HostCreateResponse\x12>\n" +
	"\x06Attach\x12\x17.geneza.v1.ClientToHost\x1a\x17.geneza.v1.HostToClient(\x010\x01\x12?\n" +
	"\x04List\x12\x1a.geneza.v1.HostListRequest\x1a\x1b.geneza.v1.HostListResponse\x128\n" +
	"\x04Kill\x12\x1a.geneza.v1.HostKillRequest\x1a\x14.geneza.v1.HostEmpty\x12=\n" +
	"\x06Health\x12\x14.geneza.v1.HostEmpty\x1a\x1d.geneza.v1.HostHealthResponse\x12:\n" +
	"\vApplyPolicy\x12\x15.geneza.v1.HostPolicy\x1a\x14.geneza.v1.HostEmptyB2Z0osie.cloud/geneza/internal/pb/geneza/v1;genezav1b\x06proto3"

var (
	file_geneza_v1_sessionhost_proto_rawDescOnce sync.Once
	file_geneza_v1_sessionhost_proto_rawDescData []byte
)

func file_geneza_v1_sessionhost_proto_rawDescGZIP() []byte {
	file_geneza_v1_sessionhost_proto_rawDescOnce.Do(func() {
		file_geneza_v1_sessionhost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geneza_v1_sessionhost_proto_rawDesc), len(file_geneza_v1_sessionhost_proto_rawDesc)))
	})
	return file_geneza_v1_sessionhost_proto_rawDescData
}

var file_geneza_v1_sessionhost_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_geneza_v1_sessionhost_proto_goTypes = []any{
	(*HostCreateRequest)(nil),  // 0: geneza.v1.HostCreateRequest
	(*HostCreateResponse)(nil), // 1: geneza.v1.HostCreateResponse
	(*ClientToHost)(nil),       // 2: geneza.v1.ClientToHost
	(*AttachOpen)(nil),         // 3: geneza.v1.AttachOpen
	(*Input)(nil),              // 4: geneza.v1.Input
	(*Resize)(nil),             // 5: geneza.v1.Resize
	(*Signal)(nil),             // 6: geneza.v1.Signal
	(*Detach)(nil),             // 7: geneza.v1.Detach
	(*Stdin_EOF)(nil),          // 8: geneza.v1.Stdin_EOF
	(*HostToClient)(nil),       // 9: geneza.v1.HostToClient
	(*Snapshot)(nil),           // 10: geneza.v1.Snapshot
	(*Output)(nil),             // 11: geneza.v1.Output
	(*Stderr)(nil),             // 12: geneza.v1.Stderr
	(*Exit)(nil),               // 13: geneza.v1.Exit
	(*InputAck)(nil),           // 14: geneza.v1.InputAck
	(*HostSessionInfo)(nil),    // 15: geneza.v1.HostSessionInfo
	(*HostListRequest)(nil),    // 16: geneza.v1.HostListRequest
	(*HostListResponse)(nil),   // 17: geneza.v1.HostListResponse
	(*HostKillRequest)(nil),    // 18: geneza.v1.HostKillRequest
	(*HostHealthResponse)(nil), // 19: geneza.v1.HostHealthResponse
	(*HostPolicy)(nil),         // 20: geneza.v1.HostPolicy
	(*HostEmpty)(nil),          // 21: geneza.v1.HostEmpty
	nil,                        // 22: geneza.v1.HostCreateRequest.EnvEntry
}
var file_geneza_v1_sessionhost_proto_depIdxs = []int32{
	22, // 0: geneza.v1.HostCreateRequest.env:type_name -> geneza.v1.HostCreateRequest.EnvEntry
	3,  // 1: geneza.v1.ClientToHost.open:type_name -> geneza.v1.AttachOpen
	4,  // 2: geneza.v1.ClientToHost.input:type_name -> geneza.v1.Input
	5,  // 3: geneza.v1.ClientToHost.resize:type_name -> geneza.v1.Resize
	6,  // 4: geneza.v1.ClientToHost.signal:type_name -> geneza.v1.Signal
	7,  // 5: geneza.v1.ClientToHost.detach:type_name -> geneza.v1.Detach
	8,  // 6: geneza.v1.ClientToHost.stdin_eof:type_name -> geneza.v1.Stdin_EOF
	10, // 7: geneza.v1.HostToClient.snapshot:type_name -> geneza.v1.Snapshot
	11, // 8: geneza.v1.HostToClient.output:type_name -> geneza.v1.Output
	12, // 9: geneza.v1.HostToClient.stderr:type_name -> geneza.v1.Stderr
	13, // 10: geneza.v1.HostToClient.exit:type_name -> geneza.v1.Exit
	14, // 11: geneza.v1.HostToClient.input_ack:type_name -> geneza.v1.InputAck
	15, // 12: geneza.v1.HostListResponse.sessions:type_name -> geneza.v1.HostSessionInfo
	0,  // 13: geneza.v1.SessionHost.Create:input_type -> geneza.v1.HostCreateRequest
	2,  // 14: geneza.v1.SessionHost.Attach:input_type -> geneza.v1.ClientToHost
	16, // 15: geneza.v1.SessionHost.List:input_type -> geneza.v1.HostListRequest
	18, // 16: geneza.v1.SessionHost.Kill:input_type -> geneza.v1.HostKillRequest
	21, // 17: geneza.v1.SessionHost.Health:input_type -> geneza.v1.HostEmpty
	20, // 18: geneza.v1.SessionHost.ApplyPolicy:input_type -> geneza.v1.HostPolicy
	1,  // 19: geneza.v1.SessionHost.Create:output_type -> geneza.v1.HostCreateResponse
	9,  // 20: geneza.v1.SessionHost.Attach:output_type -> geneza.v1.HostToClient
	17, // 21: geneza.v1.SessionHost.List:output_type -> geneza.v1.HostListResponse
	21, // 22: geneza.v1.SessionHost.Kill:output_type -> geneza.v1.HostEmpty
	19, // 23: geneza.v1.SessionHost.Health:output_type -> geneza.v1.HostHealthResponse
	21, // 24: geneza.v1.SessionHost.ApplyPolicy:output_type -> geneza.v1.HostEmpty
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_geneza_v1_sessionhost_proto_init() }
func file_geneza_v1_sessionhost_proto_init() {
	if File_geneza_v1_sessionhost_proto != nil {
		return
	}
	file_geneza_v1_sessionhost_proto_msgTypes[2].OneofWrappers = []any{
		(*ClientToHost_Open)(nil),
		(*ClientToHost_Input)(nil),
		(*ClientToHost_Resize)(nil),
		(*ClientToHost_Signal)(nil),
		(*ClientToHost_Detach)(nil),
		(*ClientToHost_StdinEof)(nil),
	}
	file_geneza_v1_sessionhost_proto_msgTypes[9].OneofWrappers = []any{
		(*HostToClient_Snapshot)(nil),
		(*HostToClient_Output)(nil),
		(*HostToClient_Stderr)(nil),
		(*HostToClient_Exit)(nil),
		(*HostToClient_InputAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geneza_v1_sessionhost_proto_rawDesc), len(file_geneza_v1_sessionhost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geneza_v1_sessionhost_proto_goTypes,
		DependencyIndexes: file_geneza_v1_sessionhost_proto_depIdxs,
		MessageInfos:      file_geneza_v1_sessionhost_proto_msgTypes,
	}.Build()
	File_geneza_v1_sessionhost_proto = out.File
	file_geneza_v1_sessionhost_proto_goTypes = nil
	file_geneza_v1_sessionhost_proto_depIdxs = nil
}
