// Agent-internal session host API (gRPC over a unix socket).
//
// The session host is a small, stable, separately-supervised process that
// owns live PTYs and their buffers so that worker restarts (binary updates)
// never kill live sessions. The worker bridges tunnel channels to this API.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: geneza/v1/sessionhost.proto

package genezav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionHost_Create_FullMethodName      = "/geneza.v1.SessionHost/Create"
	SessionHost_Attach_FullMethodName      = "/geneza.v1.SessionHost/Attach"
	SessionHost_List_FullMethodName        = "/geneza.v1.SessionHost/List"
	SessionHost_Kill_FullMethodName        = "/geneza.v1.SessionHost/Kill"
	SessionHost_Health_FullMethodName      = "/geneza.v1.SessionHost/Health"
	SessionHost_ApplyPolicy_FullMethodName = "/geneza.v1.SessionHost/ApplyPolicy"
	SessionHost_SetCaps_FullMethodName     = "/geneza.v1.SessionHost/SetCaps"
)

// SessionHostClient is the client API for SessionHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionHostClient interface {
	Create(ctx context.Context, in *HostCreateRequest, opts ...grpc.CallOption) (*HostCreateResponse, error)
	// Attach a client to a session. First ClientToHost MUST be open.
	// The host immediately replies with Snapshot (pty mode) carrying the
	// current screen state + the seq it corresponds to, then streams Output.
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientToHost, HostToClient], error)
	List(ctx context.Context, in *HostListRequest, opts ...grpc.CallOption) (*HostListResponse, error)
	Kill(ctx context.Context, in *HostKillRequest, opts ...grpc.CallOption) (*HostEmpty, error)
	Health(ctx context.Context, in *HostEmpty, opts ...grpc.CallOption) (*HostHealthResponse, error)
	// ApplyPolicy pushes agent policy knobs (caps, TTLs) from cluster config.
	ApplyPolicy(ctx context.Context, in *HostPolicy, opts ...grpc.CallOption) (*HostEmpty, error)
	// SetCaps applies a downgrade to a live session at the HOST (authoritative):
	// a read-only flip is honored even for a DETACHED PTY with no agent bridge,
	// and persists across worker restarts (the session realtime PEP). Reattach
	// re-reads host caps and never re-widens from the static grant.
	SetCaps(ctx context.Context, in *HostSetCapsRequest, opts ...grpc.CallOption) (*HostEmpty, error)
}

type sessionHostClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionHostClient(cc grpc.ClientConnInterface) SessionHostClient {
	return &sessionHostClient{cc}
}

func (c *sessionHostClient) Create(ctx context.Context, in *HostCreateRequest, opts ...grpc.CallOption) (*HostCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostCreateResponse)
	err := c.cc.Invoke(ctx, SessionHost_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHostClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientToHost, HostToClient], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SessionHost_ServiceDesc.Streams[0], SessionHost_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientToHost, HostToClient]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionHost_AttachClient = grpc.BidiStreamingClient[ClientToHost, HostToClient]

func (c *sessionHostClient) List(ctx context.Context, in *HostListRequest, opts ...grpc.CallOption) (*HostListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostListResponse)
	err := c.cc.Invoke(ctx, SessionHost_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHostClient) Kill(ctx context.Context, in *HostKillRequest, opts ...grpc.CallOption) (*HostEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostEmpty)
	err := c.cc.Invoke(ctx, SessionHost_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHostClient) Health(ctx context.Context, in *HostEmpty, opts ...grpc.CallOption) (*HostHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostHealthResponse)
	err := c.cc.Invoke(ctx, SessionHost_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHostClient) ApplyPolicy(ctx context.Context, in *HostPolicy, opts ...grpc.CallOption) (*HostEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostEmpty)
	err := c.cc.Invoke(ctx, SessionHost_ApplyPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionHostClient) SetCaps(ctx context.Context, in *HostSetCapsRequest, opts ...grpc.CallOption) (*HostEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostEmpty)
	err := c.cc.Invoke(ctx, SessionHost_SetCaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionHostServer is the server API for SessionHost service.
// All implementations must embed UnimplementedSessionHostServer
// for forward compatibility.
type SessionHostServer interface {
	Create(context.Context, *HostCreateRequest) (*HostCreateResponse, error)
	// Attach a client to a session. First ClientToHost MUST be open.
	// The host immediately replies with Snapshot (pty mode) carrying the
	// current screen state + the seq it corresponds to, then streams Output.
	Attach(grpc.BidiStreamingServer[ClientToHost, HostToClient]) error
	List(context.Context, *HostListRequest) (*HostListResponse, error)
	Kill(context.Context, *HostKillRequest) (*HostEmpty, error)
	Health(context.Context, *HostEmpty) (*HostHealthResponse, error)
	// ApplyPolicy pushes agent policy knobs (caps, TTLs) from cluster config.
	ApplyPolicy(context.Context, *HostPolicy) (*HostEmpty, error)
	// SetCaps applies a downgrade to a live session at the HOST (authoritative):
	// a read-only flip is honored even for a DETACHED PTY with no agent bridge,
	// and persists across worker restarts (the session realtime PEP). Reattach
	// re-reads host caps and never re-widens from the static grant.
	SetCaps(context.Context, *HostSetCapsRequest) (*HostEmpty, error)
	mustEmbedUnimplementedSessionHostServer()
}

// UnimplementedSessionHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionHostServer struct{}

func (UnimplementedSessionHostServer) Create(context.Context, *HostCreateRequest) (*HostCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSessionHostServer) Attach(grpc.BidiStreamingServer[ClientToHost, HostToClient]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedSessionHostServer) List(context.Context, *HostListRequest) (*HostListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSessionHostServer) Kill(context.Context, *HostKillRequest) (*HostEmpty, error) {
	return nil, status.Error(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedSessionHostServer) Health(context.Context, *HostEmpty) (*HostHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSessionHostServer) ApplyPolicy(context.Context, *HostPolicy) (*HostEmpty, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPolicy not implemented")
}
func (UnimplementedSessionHostServer) SetCaps(context.Context, *HostSetCapsRequest) (*HostEmpty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCaps not implemented")
}
func (UnimplementedSessionHostServer) mustEmbedUnimplementedSessionHostServer() {}
func (UnimplementedSessionHostServer) testEmbeddedByValue()                     {}

// UnsafeSessionHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionHostServer will
// result in compilation errors.
type UnsafeSessionHostServer interface {
	mustEmbedUnimplementedSessionHostServer()
}

func RegisterSessionHostServer(s grpc.ServiceRegistrar, srv SessionHostServer) {
	// If the following call panics, it indicates UnimplementedSessionHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionHost_ServiceDesc, srv)
}

func _SessionHost_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHostServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHost_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHostServer).Create(ctx, req.(*HostCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHost_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SessionHostServer).Attach(&grpc.GenericServerStream[ClientToHost, HostToClient]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionHost_AttachServer = grpc.BidiStreamingServer[ClientToHost, HostToClient]

func _SessionHost_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHostServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHost_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHostServer).List(ctx, req.(*HostListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHost_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostKillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHostServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHost_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHostServer).Kill(ctx, req.(*HostKillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHost_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHostServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHost_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHostServer).Health(ctx, req.(*HostEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHost_ApplyPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostPolicy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHostServer).ApplyPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHost_ApplyPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHostServer).ApplyPolicy(ctx, req.(*HostPolicy))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionHost_SetCaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostSetCapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionHostServer).SetCaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionHost_SetCaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionHostServer).SetCaps(ctx, req.(*HostSetCapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionHost_ServiceDesc is the grpc.ServiceDesc for SessionHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geneza.v1.SessionHost",
	HandlerType: (*SessionHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SessionHost_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SessionHost_List_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _SessionHost_Kill_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SessionHost_Health_Handler,
		},
		{
			MethodName: "ApplyPolicy",
			Handler:    _SessionHost_ApplyPolicy_Handler,
		},
		{
			MethodName: "SetCaps",
			Handler:    _SessionHost_SetCaps_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _SessionHost_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "geneza/v1/sessionhost.proto",
}
